import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';
import 'package:url_launcher/url_launcher.dart';

const primary = Color(0xFF00A889);
const dark = Color(0xFF10241F);
const muted = Color(0xFF687873);
const bg = Color(0xFFF5FAF8);
const mint = Color(0xFFE4F8F2);
const version = '1.0.2';
const website = 'https://shanpalia.github.io/WebsitePaliaAPK_V.2/';
const updateUrl = 'https://shanpalia.github.io/WebsitePaliaAPK_V.2/rentflow_update_v2.json';

int i(dynamic v) => v is num ? v.toInt() : int.tryParse('$v') ?? 0;
double d(dynamic v) => v is num ? v.toDouble() : double.tryParse('$v') ?? 0;
String money(dynamic v) => '₹${d(v).toStringAsFixed(0)}';

Future<void> main() async { WidgetsFlutterBinding.ensureInitialized(); runApp(const RentFlowApp()); }

class RentFlowApp extends StatelessWidget {
  const RentFlowApp({super.key});
  @override Widget build(BuildContext context) => MaterialApp(debugShowCheckedModeBanner:false,title:'RentFlow',theme:ThemeData(useMaterial3:true,scaffoldBackgroundColor:bg,colorScheme:ColorScheme.fromSeed(seedColor:primary)),home:const Splash());
}

class Splash extends StatefulWidget { const Splash({super.key}); @override State<Splash> createState()=>_SplashState(); }
class _SplashState extends State<Splash> {
  @override void initState(){super.initState(); Future.delayed(const Duration(milliseconds:1200),(){if(!mounted)return; Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const AppShell()));});}
  @override Widget build(BuildContext c)=>Scaffold(backgroundColor:Colors.white,body:Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Container(width:100,height:100,decoration:BoxDecoration(color:primary,borderRadius:BorderRadius.circular(28)),child:const Icon(Icons.swap_horiz_rounded,color:Colors.white,size:62)),const SizedBox(height:18),const Text('RentFlow',style:TextStyle(fontSize:34,fontWeight:FontWeight.w900,color:dark)),const Text('By PaliaAPK HUB',style:TextStyle(color:primary,fontWeight:FontWeight.w800)),const Text('Developer by ShanPalia',style:TextStyle(color:muted))])));
}

class Store {
  late SharedPreferences p; List<Map<String,dynamic>> items=[]; List<Map<String,dynamic>> customers=[]; List<Map<String,dynamic>> rentals=[]; String shop=''; String owner=''; String phone='';
  Future<void> load() async { p=await SharedPreferences.getInstance(); shop=p.getString('shop')??''; owner=p.getString('owner')??''; phone=p.getString('phone')??''; items=_list('items'); customers=_list('customers'); rentals=_list('rentals'); }
  List<Map<String,dynamic>> _list(String key){try{final x=jsonDecode(p.getString(key)??'[]'); return x is List?x.whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList():[];}catch(_){return[];}}
  Future<void> save() async {await p.setString('items',jsonEncode(items));await p.setString('customers',jsonEncode(customers));await p.setString('rentals',jsonEncode(rentals));}
}

class AppShell extends StatefulWidget { const AppShell({super.key}); @override State<AppShell> createState()=>_AppShellState(); }
class _AppShellState extends State<AppShell>{final s=Store();int tab=0;bool ready=false;@override void initState(){super.initState();s.load().then((_){if(mounted)setState(()=>ready=true);});}
  @override Widget build(BuildContext c){if(!ready)return const Scaffold(body:Center(child:CircularProgressIndicator(color:primary)));final pages=[Home(s:s),Items(s:s),Customers(s:s),Reports(s:s),Settings(s:s)];return PopScope(canPop:tab==0,onPopInvokedWithResult:(did,_) {if(!did&&tab!=0)setState(()=>tab=0);},child:Scaffold(body:pages[tab],bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(v)=>setState(()=>tab=v),destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Home'),NavigationDestination(icon:Icon(Icons.inventory_2_outlined),selectedIcon:Icon(Icons.inventory_2),label:'Items'),NavigationDestination(icon:Icon(Icons.people_outline),selectedIcon:Icon(Icons.people),label:'Customers'),NavigationDestination(icon:Icon(Icons.bar_chart_outlined),selectedIcon:Icon(Icons.bar_chart),label:'Reports'),NavigationDestination(icon:Icon(Icons.settings_outlined),selectedIcon:Icon(Icons.settings),label:'Settings')])));}
}

class Home extends StatelessWidget{final Store s;const Home({required this.s,super.key});@override Widget build(BuildContext c){final open=s.rentals.where((r)=>i(r['received'])<i(r['qty'])).length;return SafeArea(child:ListView(padding:const EdgeInsets.all(18),children:[Text(s.shop.isEmpty?'RentFlow':s.shop,style:const TextStyle(fontSize:28,fontWeight:FontWeight.w900,color:dark)),const Text('Rental Management',style:TextStyle(color:muted)),const SizedBox(height:18),Row(children:[stat('Items','${s.items.length}'),stat('Customers','${s.customers.length}'),stat('Issued','$open')]),const SizedBox(height:16),FilledButton.icon(onPressed:()=>rentalDialog(c,s),icon:const Icon(Icons.add),label:const Text('New Rental'),style:FilledButton.styleFrom(backgroundColor:primary,minimumSize:const Size.fromHeight(54))),const SizedBox(height:14),Row(children:[quick('Item',Icons.inventory_2,()=>itemDialog(c,s)),quick('Customer',Icons.person_add,()=>customerDialog(c,s)),quick('Invoice',Icons.receipt_long,()=>invoiceDialog(c,s)),quick('Receive',Icons.assignment_return,()=>receiveDialog(c,s))]),const SizedBox(height:20),const Text('Recent Rentals',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),...s.rentals.reversed.take(8).map((r)=>Card(child:ListTile(title:Text('${r['customer']}'),subtitle:Text('${r['item']} • Qty ${r['qty']}'),trailing:Text(money(r['amount']))))) ]));}}

Widget stat(String a,String b)=>Expanded(child:Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(b,style:const TextStyle(fontSize:21,fontWeight:FontWeight.w900)),Text(a,style:const TextStyle(color:muted))]))));
Widget quick(String t,IconData icon,VoidCallback fn)=>Expanded(child:InkWell(onTap:fn,child:Container(margin:const EdgeInsets.only(right:5),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(16)),child:Column(children:[Icon(icon,color:primary),const SizedBox(height:5),Text(t,style:const TextStyle(fontSize:11,fontWeight:FontWeight.w800))]))));
Widget header(String t,String sub)=>Padding(padding:const EdgeInsets.fromLTRB(18,18,18,8),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(fontSize:30,fontWeight:FontWeight.w900,color:dark)),Text(sub,style:const TextStyle(color:muted))]));

class Items extends StatelessWidget{final Store s;const Items({required this.s,super.key});@override Widget build(BuildContext c)=>SafeArea(child:Column(children:[header('Items','Rental inventory'),Expanded(child:s.items.isEmpty?const Center(child:Text('No items added yet')):ListView.builder(itemCount:s.items.length,itemBuilder:(_,n){final x=s.items[n];return ListTile(leading:const CircleAvatar(backgroundColor:mint,child:Icon(Icons.inventory_2,color:primary)),title:Text('${x['name']}',style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('Qty ${i(x['qty'])} • Rent ${money(x['rent'])}'));})),bottom('Add Item',()=>itemDialog(c,s))]));}
class Customers extends StatelessWidget{final Store s;const Customers({required this.s,super.key});@override Widget build(BuildContext c)=>SafeArea(child:Column(children:[header('Customers','Customer records'),Expanded(child:s.customers.isEmpty?const Center(child:Text('No customers added yet')):ListView.builder(itemCount:s.customers.length,itemBuilder:(_,n){final x=s.customers[n];return ListTile(onTap:()=>customerReport(c,s,'${x['name']}'),leading:const CircleAvatar(backgroundColor:mint,child:Icon(Icons.person,color:primary)),title:Text('${x['name']}',style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${x['phone']??''}'),trailing:const Icon(Icons.chevron_right));})),bottom('New Customer',()=>customerDialog(c,s))]));}
class Reports extends StatelessWidget{final Store s;const Reports({required this.s,super.key});@override Widget build(BuildContext c){return SafeArea(child:ListView(padding:const EdgeInsets.all(18),children:[header('Reports','Date, day and amount'),...s.rentals.reversed.map((r)=>Card(child:ListTile(title:Text('${r['customer']} • ${r['item']}'),subtitle:Text('${r['date']} • Qty ${r['qty']}'),trailing:Text(money(r['amount']))))) ]));}}
Widget bottom(String t,VoidCallback fn)=>Padding(padding:const EdgeInsets.fromLTRB(18,8,18,14),child:FilledButton.icon(onPressed:fn,icon:const Icon(Icons.add),label:Text(t),style:FilledButton.styleFrom(backgroundColor:primary,minimumSize:const Size.fromHeight(52))));

class Settings extends StatelessWidget{final Store s;const Settings({required this.s,super.key});@override Widget build(BuildContext c)=>SafeArea(child:ListView(padding:const EdgeInsets.all(18),children:[const Text('Settings',style:TextStyle(fontSize:31,fontWeight:FontWeight.w900,color:dark)),const SizedBox(height:16),Card(child:ListTile(leading:const CircleAvatar(backgroundColor:mint,child:Icon(Icons.store,color:primary)),title:Text(s.shop.isEmpty?'Your Shop':s.shop,style:const TextStyle(fontWeight:FontWeight.w900)),subtitle:Text('${s.owner}\n${s.phone}'))),const SizedBox(height:12),Card(child:Column(children:[ListTile(leading:const Icon(Icons.system_update,color:primary),title:const Text('Check for App Update',style:TextStyle(fontWeight:FontWeight.w800)),subtitle:const Text('Check the latest RentFlow version'),onTap:()=>checkUpdate(c)),ListTile(leading:const Icon(Icons.language,color:primary),title:const Text('PaliaAPK HUB Website'),onTap:()=>launchUrl(Uri.parse(website),mode:LaunchMode.externalApplication)),const ListTile(leading:Icon(Icons.info_outline,color:primary),title:Text('RentFlow'),subtitle:Text('By PaliaAPK HUB • Developer by ShanPalia'),)])]));}

Future<void> checkUpdate(BuildContext c)async{showDialog(context:c,barrierDismissible:false,builder:(_)=>const AlertDialog(content:Row(children:[CircularProgressIndicator(),SizedBox(width:16),Text('Checking for updates...')])));try{final r=await http.get(Uri.parse(updateUrl)).timeout(const Duration(seconds:8));if(!c.mounted)return;Navigator.pop(c);if(r.statusCode!=200){ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Could not check for updates')));return;}final data=jsonDecode(r.body);final latest='${data['version']??version}';if(latest!=version){showDialog(context:c,builder:(_)=>AlertDialog(title:const Text('Update available'),content:Text('Version $latest is available.'),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Later')),FilledButton(onPressed:()=>launchUrl(Uri.parse('${data['url']??website}'),mode:LaunchMode.externalApplication),child:const Text('Update'))]));}else{showDialog(context:c,builder:(_)=>AlertDialog(title:const Text('Up to date'),content:Text('RentFlow $version is the latest version.'),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('OK'))]));}}catch(_){if(c.mounted){Navigator.pop(c);ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Could not check for updates. Please try again later.')));}}}

Future<void> itemDialog(BuildContext c,Store s)async{final n=TextEditingController(),q=TextEditingController(text:'1'),r=TextEditingController();final ok=await showDialog<bool>(context:c,builder:(_)=>AlertDialog(title:const Text('Add Rental Item'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Item name')),TextField(controller:q,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Quantity')),TextField(controller:r,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Rent price'))]),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Save'))]));if(ok==true&&n.text.trim().isNotEmpty){s.items.add({'name':n.text.trim(),'qty':i(q.text),'rent':d(r.text)});await s.save();if(c.mounted)(c as Element).markNeedsBuild();}}

Future<void> customerDialog(BuildContext c,Store s)async{final n=TextEditingController(),p=TextEditingController();final ok=await showDialog<bool>(context:c,builder:(_)=>AlertDialog(title:const Text('New Customer'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Customer name')),TextField(controller:p,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'Phone'))]),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Save'))]));if(ok==true&&n.text.trim().isNotEmpty){s.customers.add({'name':n.text.trim(),'phone':p.text.trim()});await s.save();}}

Future<void> rentalDialog(BuildContext c,Store s)async{if(s.items.isEmpty||s.customers.isEmpty){ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Add an item and customer first.')));return;}String customer='${s.customers.first['name']}',item='${s.items.first['name']}';final q=TextEditingController(text:'1');final ok=await showDialog<bool>(context:c,builder:(_)=>StatefulBuilder(builder:(c,set)=>AlertDialog(title:const Text('New Rental'),content:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<String>(initialValue:customer,items:s.customers.map((x)=>DropdownMenuItem(value:'${x['name']}',child:Text('${x['name']}'))).toList(),onChanged:(v)=>set(()=>customer=v??customer)),DropdownButtonFormField<String>(initialValue:item,items:s.items.map((x)=>DropdownMenuItem(value:'${x['name']}',child:Text('${x['name']}'))).toList(),onChanged:(v)=>set(()=>item=v??item)),TextField(controller:q,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Quantity'))]),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Issue'))])));if(ok==true){final x=s.items.firstWhere((e)=>e['name']==item);final qty=i(q.text);s.rentals.add({'customer':customer,'item':item,'qty':qty,'received':0,'amount':d(x['rent'])*qty,'date':DateTime.now().toString().substring(0,10)});await s.save();}}

Future<void> receiveDialog(BuildContext c,Store s)async{final open=s.rentals.where((r)=>i(r['received'])<i(r['qty'])).toList();if(open.isEmpty){ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('No issued rental found.')));return;}final r=open.first;r['received']=r['qty'];await s.save();ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Item received successfully.')));}
Future<void> invoiceDialog(BuildContext c,Store s)async{final r=s.rentals.isEmpty?null:s.rentals.last;showDialog(context:c,builder:(_)=>AlertDialog(title:const Text('Invoice'),content:Text(r==null?'No rental yet':'Customer: ${r['customer']}\nItem: ${r['item']}\nDate: ${r['date']}\nQty: ${r['qty']}\nAmount: ${money(r['amount'])}'),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Close'))]));}
Future<void> customerReport(BuildContext c,Store s,String customer)async{final rows=s.rentals.where((r)=>'${r['customer']}'==customer).toList();showDialog(context:c,builder:(_)=>AlertDialog(title:Text('$customer Report'),content:SizedBox(width:360,child:rows.isEmpty?const Text('No rental history.'):ListView(shrinkWrap:true,children:rows.map((r)=>ListTile(title:Text('${r['item']} • Qty ${r['qty']}'),subtitle:Text('${r['date']} • ${r['received']}/${r['qty']} received'),trailing:Text(money(r['amount'])))).toList())),actions:[FilledButton(onPressed:()=>Navigator.pop(c),child:const Text('Close'))]));}
