import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:url_launcher/url_launcher.dart';

const primary = Color(0xFF00A889);
const mint = Color(0xFFE8F8F3);
const bg = Color(0xFFF5F9F7);
const ink = Color(0xFF14211D);
const muted = Color(0xFF71807B);
const websiteUrl = 'https://shanpalia.github.io/WebsitePaliaAPK_V.2/';

void main() => runApp(const RentFlowApp());

class RentFlowApp extends StatelessWidget {
  const RentFlowApp({super.key});
  @override
  Widget build(BuildContext context) => MaterialApp(
    debugShowCheckedModeBanner: false,
    title: 'RentFlow',
    theme: ThemeData(useMaterial3: true, scaffoldBackgroundColor: bg, colorScheme: ColorScheme.fromSeed(seedColor: primary)),
    home: const SplashGate(),
  );
}

class SplashGate extends StatefulWidget { const SplashGate({super.key}); @override State<SplashGate> createState() => _SplashGateState(); }
class _SplashGateState extends State<SplashGate> {
  @override void initState() { super.initState(); Future.delayed(const Duration(milliseconds: 1600), () { if (mounted) Navigator.of(context).pushReplacement(MaterialPageRoute(builder: (_) => const Shell())); }); }
  @override Widget build(BuildContext context) => const Scaffold(backgroundColor: Colors.white, body: Center(child: Column(mainAxisSize: MainAxisSize.min, children: [Brand(size: 108), SizedBox(height: 20), Text('RentFlow', style: TextStyle(fontSize: 40, fontWeight: FontWeight.w900, color: ink)), SizedBox(height: 6), Text('By PaliaAPK HUB', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: primary)), SizedBox(height: 6), Text('Developer by ShanPalia', style: TextStyle(fontSize: 14, color: muted))])));
}

class Brand extends StatelessWidget { final double size; const Brand({required this.size, super.key}); @override Widget build(BuildContext context) => Container(width: size, height: size, decoration: BoxDecoration(color: primary, borderRadius: BorderRadius.circular(size * .25), boxShadow: const [BoxShadow(color: Color(0x2600A889), blurRadius: 18, offset: Offset(0, 8))]), child: Icon(Icons.swap_horiz_rounded, color: Colors.white, size: size * .58)); }

class DB {
  late SharedPreferences prefs;
  List<Map<String, dynamic>> items = [];
  List<Map<String, dynamic>> customers = [];
  List<Map<String, dynamic>> rentals = [];
  Future<void> load() async { prefs = await SharedPreferences.getInstance(); items = read('items'); customers = read('customers'); rentals = read('rentals'); }
  List<Map<String, dynamic>> read(String key) { final s = prefs.getString(key); if (s == null) return []; return (jsonDecode(s) as List).map((e) => Map<String, dynamic>.from(e)).toList(); }
  Future<void> save() async { await prefs.setString('items', jsonEncode(items)); await prefs.setString('customers', jsonEncode(customers)); await prefs.setString('rentals', jsonEncode(rentals)); }
}
int asInt(dynamic v) => v is int ? v : int.tryParse('$v') ?? 0;
double asDouble(dynamic v) => v is num ? v.toDouble() : double.tryParse('$v') ?? 0;
String money(dynamic v) { final d = asDouble(v); return d == d.roundToDouble() ? d.toInt().toString() : d.toStringAsFixed(2); }
String today() { final d = DateTime.now(); return '${d.day.toString().padLeft(2, '0')}/${d.month.toString().padLeft(2, '0')}/${d.year}'; }

class Shell extends StatefulWidget { const Shell({super.key}); @override State<Shell> createState() => _ShellState(); }
class _ShellState extends State<Shell> {
  final db = DB(); int tab = 0; bool loading = true; DateTime? lastBack;
  @override void initState() { super.initState(); load(); }
  Future<void> load() async { await db.load(); if (mounted) setState(() => loading = false); }
  void refresh() => setState(() {});
  Future<bool> handleBack() async { if (tab != 0) { setState(() => tab = 0); return false; } final now = DateTime.now(); if (lastBack != null && now.difference(lastBack!) < const Duration(seconds: 2)) return true; lastBack = now; if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Press back again to exit'), duration: Duration(seconds: 2))); return false; }
  @override Widget build(BuildContext context) {
    if (loading) return const Scaffold(body: Center(child: CircularProgressIndicator(color: primary)));
    final pages = [Home(db: db, refresh: refresh, selectTab: (i) => setState(() => tab = i)), ItemsPage(db: db, refresh: refresh), CustomersPage(db: db, refresh: refresh), ReportsPage(db: db)];
    return PopScope<bool>(canPop: false, onPopInvokedWithResult: (didPop, result) async { if (!didPop) { final allow = await handleBack(); if (allow && context.mounted) Navigator.of(context).maybePop(); } }, child: Scaffold(body: IndexedStack(index: tab, children: pages), bottomNavigationBar: NavigationBar(selectedIndex: tab, onDestinationSelected: (i) => setState(() => tab = i), indicatorColor: mint, destinations: const [NavigationDestination(icon: Icon(Icons.home_outlined), selectedIcon: Icon(Icons.home_rounded), label: 'Home'), NavigationDestination(icon: Icon(Icons.inventory_2_outlined), selectedIcon: Icon(Icons.inventory_2_rounded), label: 'Items'), NavigationDestination(icon: Icon(Icons.people_outline), selectedIcon: Icon(Icons.people_rounded), label: 'Customers'), NavigationDestination(icon: Icon(Icons.analytics_outlined), selectedIcon: Icon(Icons.analytics_rounded), label: 'Reports')]));
  }
}

class Home extends StatelessWidget {
  final DB db; final VoidCallback refresh; final ValueChanged<int> selectTab;
  const Home({required this.db, required this.refresh, required this.selectTab, super.key});
  @override Widget build(BuildContext context) {
    final total = db.items.fold<int>(0, (s, x) => s + asInt(x['qty'])); final available = db.items.fold<int>(0, (s, x) => s + asInt(x['available'])); final issued = total - available; final due = db.rentals.fold<int>(0, (s, x) => s + asInt(x['qty']) - asInt(x['received']));
    return SafeArea(child: CustomScrollView(slivers: [
      SliverPadding(padding: const EdgeInsets.fromLTRB(20, 18, 20, 0), sliver: SliverToBoxAdapter(child: Row(children: [const Brand(size: 52), const SizedBox(width: 12), const Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('RentFlow', style: TextStyle(fontSize: 28, fontWeight: FontWeight.w900)), Text('Rental management', style: TextStyle(color: muted))])), IconButton(onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (_) => const SettingsPage())), icon: const Icon(Icons.settings_outlined)), IconButton(onPressed: () => showAbout(context), icon: const Icon(Icons.info_outline_rounded))]))),
      SliverPadding(padding: const EdgeInsets.fromLTRB(20, 18, 20, 0), sliver: SliverToBoxAdapter(child: Container(padding: const EdgeInsets.all(22), decoration: BoxDecoration(gradient: const LinearGradient(colors: [Color(0xFFE9FAF5), Color(0xFFDDF5ED)]), borderRadius: BorderRadius.circular(26)), child: const Row(children: [Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('RENTAL MANAGEMENT', style: TextStyle(color: primary, fontSize: 12, fontWeight: FontWeight.w900, letterSpacing: 1.1)), SizedBox(height: 8), Text('Run your rental\nbusiness smarter.', style: TextStyle(fontSize: 27, height: 1.08, fontWeight: FontWeight.w900, color: ink)), SizedBox(height: 9), Text('Items, customers, rentals and invoices in one place.', style: TextStyle(color: muted, height: 1.35))])), SizedBox(width: 16), Icon(Icons.swap_horizontal_circle_rounded, color: primary, size: 58)]))),
      SliverPadding(padding: const EdgeInsets.fromLTRB(20, 16, 20, 0), sliver: SliverToBoxAdapter(child: Row(children: [Expanded(child: StatCard('Total Items', '$total', Icons.inventory_2_rounded)), const SizedBox(width: 10), Expanded(child: StatCard('Available', '$available', Icons.check_circle_rounded))]))),
      SliverPadding(padding: const EdgeInsets.fromLTRB(20, 10, 20, 0), sliver: SliverToBoxAdapter(child: Row(children: [Expanded(child: StatCard('Issued', '$issued', Icons.north_east_rounded)), const SizedBox(width: 10), Expanded(child: StatCard('Items Due', '$due', Icons.schedule_rounded))]))),
      SliverPadding(padding: const EdgeInsets.fromLTRB(20, 16, 20, 0), sliver: SliverToBoxAdapter(child: FilledButton.icon(style: FilledButton.styleFrom(backgroundColor: primary, foregroundColor: Colors.white, minimumSize: const Size.fromHeight(58), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(17))), onPressed: () => rentalForm(context, db, refresh), icon: const Icon(Icons.add_rounded), label: const Text('New Rental', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w800))))),
      SliverPadding(padding: const EdgeInsets.fromLTRB(20, 14, 20, 0), sliver: SliverToBoxAdapter(child: Row(children: [QuickAction('Add Item', Icons.inventory_2_outlined, () => itemForm(context, db, refresh)), QuickAction('Customer', Icons.person_add_alt_1_rounded, () => customerForm(context, db, refresh)), QuickAction('Invoice', Icons.receipt_long_outlined, () => invoiceList(context, db)), QuickAction('Receive', Icons.undo_rounded, () => receiveForm(context, db, refresh))]))),
      SliverPadding(padding: const EdgeInsets.fromLTRB(20, 24, 20, 10), sliver: SliverToBoxAdapter(child: Row(children: [const Expanded(child: Text('Recent Rentals', style: TextStyle(fontSize: 20, fontWeight: FontWeight.w900))), TextButton(onPressed: () => selectTab(3), child: const Text('View all'))]))),
      SliverPadding(padding: const EdgeInsets.fromLTRB(20, 0, 20, 30), sliver: SliverList.builder(itemCount: db.rentals.length > 6 ? 6 : db.rentals.length, itemBuilder: (context, index) { final r = db.rentals[db.rentals.length - 1 - index]; return Card(margin: const EdgeInsets.only(bottom: 8), child: ListTile(leading: const CircleAvatar(backgroundColor: mint, child: Icon(Icons.swap_horiz_rounded, color: primary)), title: Text('${r['customer']}', style: const TextStyle(fontWeight: FontWeight.w800)), subtitle: Text('${r['item']} • ${r['date']} • ${r['days']} day(s)'), trailing: Text('₹${money(r['amount'])}', style: const TextStyle(fontWeight: FontWeight.w900)))); }))
    ]));
  }
}
class StatCard extends StatelessWidget { final String title, value; final IconData icon; const StatCard(this.title, this.value, this.icon, {super.key}); @override Widget build(BuildContext context) => Container(height: 112, padding: const EdgeInsets.all(15), decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(18), border: Border.all(color: const Color(0xFFE4ECE8))), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Icon(icon, color: primary), const Spacer(), Text(title, style: const TextStyle(color: muted, fontSize: 13)), Text(value, style: const TextStyle(fontSize: 25, fontWeight: FontWeight.w900, color: ink))])); }
class QuickAction extends StatelessWidget { final String label; final IconData icon; final VoidCallback onTap; const QuickAction(this.label, this.icon, this.onTap, {super.key}); @override Widget build(BuildContext context) => Expanded(child: InkWell(onTap: onTap, borderRadius: BorderRadius.circular(16), child: Container(margin: const EdgeInsets.symmetric(horizontal: 3), padding: const EdgeInsets.symmetric(vertical: 13), decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(16), border: Border.all(color: const Color(0xFFE1E9E5))), child: Column(children: [Icon(icon, color: primary), const SizedBox(height: 7), Text(label, style: const TextStyle(fontSize: 11.5, fontWeight: FontWeight.w800))])))); }

class ItemsPage extends StatefulWidget { final DB db; final VoidCallback refresh; const ItemsPage({required this.db, required this.refresh, super.key}); @override State<ItemsPage> createState() => _ItemsPageState(); }
class _ItemsPageState extends State<ItemsPage> { String q = ''; @override Widget build(BuildContext context) { final list = widget.db.items.where((x) => '${x['name']} ${x['category']}'.toLowerCase().contains(q.toLowerCase())).toList(); return PageFrame(title: 'Items', subtitle: 'Manage your rental inventory', action: IconButton.filled(onPressed: () => itemForm(context, widget.db, widget.refresh), icon: const Icon(Icons.add_rounded)), children: [TextField(onChanged: (v) => setState(() => q = v), decoration: const InputDecoration(prefixIcon: Icon(Icons.search_rounded), hintText: 'Search items')), const SizedBox(height: 14), ...list.map((x) => Card(child: ListTile(leading: const CircleAvatar(backgroundColor: mint, child: Icon(Icons.inventory_2_rounded, color: primary)), title: Text('${x['name']}', style: const TextStyle(fontWeight: FontWeight.w900)), subtitle: Text('${x['category']} • ${x['type']} • ₹${money(x['rate'])}'), trailing: Text('${asInt(x['available'])}/${asInt(x['qty'])}', style: const TextStyle(fontWeight: FontWeight.w900)))) )]; } }

class CustomersPage extends StatefulWidget { final DB db; final VoidCallback refresh; const CustomersPage({required this.db, required this.refresh, super.key}); @override State<CustomersPage> createState() => _CustomersPageState(); }
class _CustomersPageState extends State<CustomersPage> { String q = ''; @override Widget build(BuildContext context) { final list = widget.db.customers.where((x) => '${x['name']} ${x['mobile']}'.toLowerCase().contains(q.toLowerCase())).toList(); return PageFrame(title: 'Customers', subtitle: 'Customer-wise rental history', action: IconButton.filled(onPressed: () => customerForm(context, widget.db, widget.refresh), icon: const Icon(Icons.person_add_alt_1_rounded)), children: [TextField(onChanged: (v) => setState(() => q = v), decoration: const InputDecoration(prefixIcon: Icon(Icons.search_rounded), hintText: 'Search customer')), const SizedBox(height: 14), ...list.map((x) => Card(child: ListTile(onTap: () => customerReport(context, widget.db, '${x['name']}'), leading: CircleAvatar(backgroundColor: mint, child: Text('${x['name']}'.isEmpty ? '?' : '${x['name']}'.substring(0, 1).toUpperCase(), style: const TextStyle(color: primary, fontWeight: FontWeight.w900))), title: Text('${x['name']}', style: const TextStyle(fontWeight: FontWeight.w900)), subtitle: Text('${x['mobile']} • Tap for full report'), trailing: const Icon(Icons.chevron_right_rounded))))]; } }

class ReportsPage extends StatefulWidget { final DB db; const ReportsPage({required this.db, super.key}); @override State<ReportsPage> createState() => _ReportsPageState(); }
class _ReportsPageState extends State<ReportsPage> { String q = ''; @override Widget build(BuildContext context) { final rows = widget.db.rentals.where((r) => '${r['customer']} ${r['item']}'.toLowerCase().contains(q.toLowerCase())).toList(); return PageFrame(title: 'Reports', subtitle: 'Date-wise rental report', action: IconButton(onPressed: () => invoiceList(context, widget.db), icon: const Icon(Icons.receipt_long_outlined)), children: [TextField(onChanged: (v) => setState(() => q = v), decoration: const InputDecoration(prefixIcon: Icon(Icons.search_rounded), hintText: 'Search customer or item')), const SizedBox(height: 14), Card(child: SingleChildScrollView(scrollDirection: Axis.horizontal, child: DataTable(columns: const [DataColumn(label: Text('Date')), DataColumn(label: Text('Customer')), DataColumn(label: Text('Item')), DataColumn(label: Text('Issued')), DataColumn(label: Text('Received')), DataColumn(label: Text('Days')), DataColumn(label: Text('Rate')), DataColumn(label: Text('Amount')), DataColumn(label: Text('Due'))], rows: rows.map((r) => DataRow(cells: [DataCell(Text('${r['date']}')), DataCell(Text('${r['customer']}')), DataCell(Text('${r['item']}')), DataCell(Text('${r['qty']}')), DataCell(Text('${r['received']}')), DataCell(Text('${r['days']}')), DataCell(Text('₹${money(r['rate'])}')), DataCell(Text('₹${money(r['amount'])}')), DataCell(Text('${asInt(r['qty']) - asInt(r['received'])}'))])).toList())))]; } }

class PageFrame extends StatelessWidget { final String title, subtitle; final Widget? action; final List<Widget> children; const PageFrame({required this.title, required this.subtitle, required this.children, this.action, super.key}); @override Widget build(BuildContext context) => SafeArea(child: ListView(padding: const EdgeInsets.fromLTRB(20, 18, 20, 30), children: [Row(children: [Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(title, style: const TextStyle(fontSize: 29, fontWeight: FontWeight.w900, color: ink)), const SizedBox(height: 3), Text(subtitle, style: const TextStyle(color: muted))])), if (action != null) action!]), const SizedBox(height: 18), ...children])); }

class SettingsPage extends StatelessWidget { const SettingsPage({super.key}); Future<void> openSite(BuildContext context) async { final ok = await launchUrl(Uri.parse(websiteUrl), mode: LaunchMode.externalApplication); if (!ok && context.mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Could not open website'))); } @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Settings', style: TextStyle(fontWeight: FontWeight.w900))), body: ListView(padding: const EdgeInsets.fromLTRB(20, 8, 20, 30), children: [const Text('Branding', style: TextStyle(color: muted, fontWeight: FontWeight.w800)), const SizedBox(height: 10), Card(child: Padding(padding: const EdgeInsets.all(18), child: Row(children: [const Brand(size: 64), const SizedBox(width: 16), const Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('RentFlow', style: TextStyle(fontSize: 24, fontWeight: FontWeight.w900)), SizedBox(height: 4), Text('By PaliaAPK HUB', style: TextStyle(color: primary, fontWeight: FontWeight.w800)), SizedBox(height: 3), Text('Developer by ShanPalia', style: TextStyle(color: muted))]))])), const SizedBox(height: 24), const Text('App Update', style: TextStyle(color: muted, fontWeight: FontWeight.w800)), const SizedBox(height: 10), Card(child: ListTile(leading: const CircleAvatar(backgroundColor: mint, child: Icon(Icons.system_update_rounded, color: primary)), title: const Text('Check for App Update', style: TextStyle(fontWeight: FontWeight.w800)), subtitle: const Text('Open PaliaAPK HUB for the latest version'), trailing: const Icon(Icons.open_in_new_rounded), onTap: () => openSite(context))), const SizedBox(height: 12), Card(child: ListTile(leading: const CircleAvatar(backgroundColor: mint, child: Icon(Icons.language_rounded, color: primary)), title: const Text('PaliaAPK HUB Website', style: TextStyle(fontWeight: FontWeight.w800)), subtitle: const Text('Website, updates and app information'), trailing: const Icon(Icons.chevron_right_rounded), onTap: () => openSite(context))) ]); }

class FormPage extends StatelessWidget { final String title; final List<Widget> children; const FormPage({required this.title, required this.children, super.key}); @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: Text(title, style: const TextStyle(fontWeight: FontWeight.w900))), body: ListView(padding: const EdgeInsets.all(20), children: children)); }
Widget field(TextEditingController c, String label, {bool number = false, int lines = 1}) => Padding(padding: const EdgeInsets.only(bottom: 12), child: TextField(controller: c, maxLines: lines, keyboardType: number ? const TextInputType.numberWithOptions(decimal: true) : TextInputType.text, decoration: InputDecoration(labelText: label)));

Future<void> itemForm(BuildContext context, DB db, VoidCallback refresh) async { final name = TextEditingController(), category = TextEditingController(), qty = TextEditingController(), rate = TextEditingController(); String type = 'Per Day'; await Navigator.push(context, MaterialPageRoute(builder: (_) => StatefulBuilder(builder: (c, set) => FormPage(title: 'Add Item', children: [field(name, 'Item Name'), field(category, 'Category'), field(qty, 'Total Quantity', number: true), field(rate, 'Rent Price', number: true), DropdownButtonFormField<String>(initialValue: type, decoration: const InputDecoration(labelText: 'Rent Type'), items: const ['Per Day', 'Per Hour', 'Per Event'].map((x) => DropdownMenuItem(value: x, child: Text(x))).toList(), onChanged: (v) => set(() => type = v ?? 'Per Day')), const SizedBox(height: 20), FilledButton(onPressed: () async { if (name.text.trim().isEmpty) return; final n = int.tryParse(qty.text) ?? 0; db.items.add({'id': DateTime.now().microsecondsSinceEpoch.toString(), 'name': name.text.trim(), 'category': category.text.trim(), 'qty': n, 'available': n, 'rate': double.tryParse(rate.text) ?? 0, 'type': type}); await db.save(); refresh(); if (c.mounted) Navigator.pop(c); }, child: const Text('Save Item'))])))); }

Future<void> customerForm(BuildContext context, DB db, VoidCallback refresh) async { final name = TextEditingController(), mobile = TextEditingController(), address = TextEditingController(); await Navigator.push(context, MaterialPageRoute(builder: (_) => FormPage(title: 'Add Customer', children: [field(name, 'Customer Name'), field(mobile, 'Mobile Number', number: true), field(address, 'Address', lines: 3), const SizedBox(height: 20), FilledButton(onPressed: () async { if (name.text.trim().isEmpty) return; db.customers.add({'name': name.text.trim(), 'mobile': mobile.text.trim(), 'address': address.text.trim()}); await db.save(); refresh(); if (context.mounted) Navigator.pop(context); }, child: const Text('Save Customer'))]))); }

Future<void> rentalForm(BuildContext context, DB db, VoidCallback refresh) async { if (db.items.isEmpty || db.customers.isEmpty) { ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Add at least one item and one customer first'))); return; } String customer = db.customers.first['name'] as String; String item = db.items.first['name'] as String; final q = TextEditingController(text: '1'), d = TextEditingController(text: '1'), r = TextEditingController(text: money(db.items.first['rate'])); await Navigator.push(context, MaterialPageRoute(builder: (_) => StatefulBuilder(builder: (c, set) => FormPage(title: 'New Rental', children: [DropdownButtonFormField<String>(initialValue: customer, decoration: const InputDecoration(labelText: 'Customer'), items: db.customers.map((x) => DropdownMenuItem(value: x['name'] as String, child: Text(x['name'] as String))).toList(), onChanged: (v) => set(() => customer = v ?? customer)), const SizedBox(height: 12), DropdownButtonFormField<String>(initialValue: item, decoration: const InputDecoration(labelText: 'Item'), items: db.items.map((x) => DropdownMenuItem(value: x['name'] as String, child: Text(x['name'] as String))).toList(), onChanged: (v) { final n = v ?? item; set(() { item = n; r.text = money(db.items.firstWhere((x) => x['name'] == n)['rate']); }); }), field(q, 'Quantity', number: true), field(d, 'Days / Hours', number: true), field(r, 'Rate', number: true), const SizedBox(height: 20), FilledButton(onPressed: () async { final qty = int.tryParse(q.text) ?? 0; final days = int.tryParse(d.text) ?? 0; final rate = double.tryParse(r.text) ?? 0; final it = db.items.firstWhere((x) => x['name'] == item); if (qty <= 0 || qty > asInt(it['available'])) { ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content: Text('Quantity is not available'))); return; } it['available'] = asInt(it['available']) - qty; db.rentals.add({'date': today(), 'customer': customer, 'item': item, 'qty': qty, 'received': 0, 'days': days, 'rate': rate, 'amount': qty * days * rate}); await db.save(); refresh(); if (c.mounted) Navigator.pop(c); }, child: const Text('Create Rental / Invoice'))])))); }

Future<void> receiveForm(BuildContext context, DB db, VoidCallback refresh) async { final active = db.rentals.where((r) => asInt(r['qty']) > asInt(r['received'])).toList(); if (active.isEmpty) { ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('No issued items to receive'))); return; } final r = active.first; final qty = TextEditingController(text: '${asInt(r['qty']) - asInt(r['received'])}'); await Navigator.push(context, MaterialPageRoute(builder: (_) => FormPage(title: 'Receive Item', children: [Card(child: ListTile(title: Text('${r['item']}', style: const TextStyle(fontWeight: FontWeight.w900)), subtitle: Text('${r['customer']} • Issued ${r['qty']} • Received ${r['received']}'))), const SizedBox(height: 14), field(qty, 'Received Quantity', number: true), const SizedBox(height: 20), FilledButton(onPressed: () async { final n = int.tryParse(qty.text) ?? 0; final remaining = asInt(r['qty']) - asInt(r['received']); if (n <= 0 || n > remaining) return; r['received'] = asInt(r['received']) + n; final it = db.items.firstWhere((x) => x['name'] == r['item']); it['available'] = asInt(it['available']) + n; await db.save(); refresh(); if (context.mounted) Navigator.pop(context); }, child: const Text('Save Received'))]))); }

void customerReport(BuildContext context, DB db, String name) { final rows = db.rentals.where((r) => r['customer'] == name).toList(); Navigator.push(context, MaterialPageRoute(builder: (_) => Scaffold(appBar: AppBar(title: Text(name, style: const TextStyle(fontWeight: FontWeight.w900))), body: ListView(padding: const EdgeInsets.all(20), children: [Card(child: Padding(padding: const EdgeInsets.all(16), child: Row(children: [Expanded(child: summary('Issued', rows.fold<int>(0, (s, r) => s + asInt(r['qty'])))), Expanded(child: summary('Received', rows.fold<int>(0, (s, r) => s + asInt(r['received'])))), Expanded(child: summary('Item Due', rows.fold<int>(0, (s, r) => s + asInt(r['qty']) - asInt(r['received']))))]))), const SizedBox(height: 14), ...rows.map((r) => Card(child: ListTile(title: Text('${r['item']}', style: const TextStyle(fontWeight: FontWeight.w900)), subtitle: Text('${r['date']} • ${r['days']} day(s) • ₹${money(r['rate'])}'), trailing: Text('₹${money(r['amount'])}\nDue ${asInt(r['qty']) - asInt(r['received'])}', textAlign: TextAlign.right)))).toList()]))); }
Widget summary(String a, int b) => Column(children: [Text('$b', style: const TextStyle(fontSize: 22, fontWeight: FontWeight.w900, color: primary)), Text(a, style: const TextStyle(fontSize: 12, color: muted))]);

void invoiceList(BuildContext context, DB db) { Navigator.push(context, MaterialPageRoute(builder: (_) => Scaffold(appBar: AppBar(title: const Text('Invoices', style: TextStyle(fontWeight: FontWeight.w900))), body: ListView(padding: const EdgeInsets.all(20), children: db.rentals.reversed.map((r) => Card(child: ListTile(leading: const CircleAvatar(backgroundColor: mint, child: Icon(Icons.receipt_long_rounded, color: primary)), title: Text('Invoice • ${r['customer']}', style: const TextStyle(fontWeight: FontWeight.w900)), subtitle: Text('${r['date']} • ${r['item']} • ${r['days']} day(s)'), trailing: Text('₹${money(r['amount'])}', style: const TextStyle(fontWeight: FontWeight.w900)))).toList()))); }
void showAbout(BuildContext context) => showAboutDialog(context: context, applicationName: 'RentFlow', applicationVersion: '1.0.0', applicationIcon: const Brand(size: 52), children: const [Text('By PaliaAPK HUB'), SizedBox(height: 6), Text('Developer by ShanPalia')]);
