import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

const teal = Color(0xFF00A982);
const mint = Color(0xFFE9FBF6);

void main() => runApp(const RentFlowApp());

class RentFlowApp extends StatelessWidget {
  const RentFlowApp({super.key});
  @override
  Widget build(BuildContext context) => MaterialApp(
    debugShowCheckedModeBanner: false,
    title: 'RentFlow',
    theme: ThemeData(useMaterial3: true, scaffoldBackgroundColor: const Color(0xFFF8FFFC), colorScheme: ColorScheme.fromSeed(seedColor: teal), fontFamily: 'sans'),
    home: const AppShell(),
  );
}

class AppShell extends StatefulWidget { const AppShell({super.key}); @override State<AppShell> createState()=>_AppShellState(); }
class _AppShellState extends State<AppShell> {
  int tab=0; final data=Store(); bool loading=true;
  @override void initState(){super.initState(); _load();}
  Future<void> _load() async {await data.load(); if(mounted)setState(()=>loading=false);}
  void refresh()=>setState((){});
  @override Widget build(BuildContext context){
    if(loading) return const Splash();
    final pages=[Home(data:data,onChanged:refresh), ItemsPage(data:data,onChanged:refresh), CustomersPage(data:data,onChanged:refresh), ReportsPage(data:data)];
    return Scaffold(body: pages[tab], bottomNavigationBar: NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[
      NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Home'),
      NavigationDestination(icon:Icon(Icons.inventory_2_outlined),selectedIcon:Icon(Icons.inventory_2),label:'Items'),
      NavigationDestination(icon:Icon(Icons.groups_outlined),selectedIcon:Icon(Icons.groups),label:'Customers'),
      NavigationDestination(icon:Icon(Icons.bar_chart_outlined),selectedIcon:Icon(Icons.bar_chart),label:'Reports'),
    ]));
  }
}
class Splash extends StatelessWidget {const Splash({super.key}); @override Widget build(BuildContext c)=>Scaffold(body:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Container(width:92,height:92,decoration:BoxDecoration(color:teal,borderRadius:BorderRadius.circular(28)),child:const Icon(Icons.swap_horiz_rounded,color:Colors.white,size:58)),const SizedBox(height:18),const Text('RentFlow',style:TextStyle(fontSize:38,fontWeight:FontWeight.w800)),const Text('By PaliaAPK HUB',style:TextStyle(color:teal,fontWeight:FontWeight.w700)),const SizedBox(height:8),const Text('Developer by ShanPalia',style:TextStyle(color:Colors.black54))])));}

class Store {
  List<Map<String,dynamic>> items=[]; List<Map<String,dynamic>> customers=[]; List<Map<String,dynamic>> rentals=[]; List<Map<String,dynamic>> invoices=[];
  late SharedPreferences p;
  Future<void> load() async {p=await SharedPreferences.getInstance(); items=_read('items');customers=_read('customers');rentals=_read('rentals');invoices=_read('invoices');}
  List<Map<String,dynamic>> _read(String k){final s=p.getString(k);if(s==null)return[];return List<Map<String,dynamic>>.from((jsonDecode(s) as List).map((e)=>Map<String,dynamic>.from(e)));}
  Future<void> save() async {for(final e in {'items':items,'customers':customers,'rentals':rentals,'invoices':invoices}.entries){await p.setString(e.key,jsonEncode(e.value));}}
  String id()=>DateTime.now().microsecondsSinceEpoch.toString();
}

class Home extends StatelessWidget {final Store data;final VoidCallback onChanged;const Home({super.key,required this.data,required this.onChanged});
  @override Widget build(BuildContext context){
    final total=data.items.fold<int>(0,(s,e)=>s+(e['qty']??0) as int); final issued=data.rentals.where((e)=>e['status']=='issued').fold<int>(0,(s,e)=>s+(e['qty']??0) as int); final due=data.rentals.where((e)=>e['status']=='issued').fold<double>(0,(s,e)=>s+(e['amount']??0) as num);
    return SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(18,16,18,24),children:[
      Row(children:[Container(width:48,height:48,decoration:BoxDecoration(color:teal,borderRadius:BorderRadius.circular(14)),child:const Icon(Icons.swap_horiz,color:Colors.white,size:30)),const SizedBox(width:10),const Expanded(child:Text('RentFlow',style:TextStyle(fontSize:27,fontWeight:FontWeight.w800))),IconButton(onPressed:()=>_business(context),icon:const Icon(Icons.settings_outlined))]),
      const SizedBox(height:12), Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:mint,borderRadius:BorderRadius.circular(20)),child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Good Morning,',style:TextStyle(color:Colors.black54,fontSize:15)),SizedBox(height:2),Text('Shop Owner',style:TextStyle(fontSize:27,fontWeight:FontWeight.w800)),Text('Manage your rental business easily',style:TextStyle(color:Colors.black54))])),
      const SizedBox(height:16),GridView.count(crossAxisCount:2,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisSpacing:10,mainAxisSpacing:10,childAspectRatio:1.8,children:[_stat('Total Items','$total',Icons.inventory_2),_stat('Available','${total-issued}',Icons.check_circle),_stat('Issued','$issued',Icons.north_east),_stat('Items Due','${data.rentals.where((e)=>e['status']=='issued').length}',Icons.schedule)]),
      const SizedBox(height:14),FilledButton.icon(style:FilledButton.styleFrom(minimumSize:const Size.fromHeight(58),backgroundColor:teal,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(18))),onPressed:()=>_rental(context),icon:const Icon(Icons.add_circle_outline),label:const Text('New Rental',style:TextStyle(fontSize:20,fontWeight:FontWeight.w700))),
      const SizedBox(height:12),Row(children:[Expanded(child:_action(context,'Add Item',Icons.inventory_2_outlined,()=>_addItem(context))),Expanded(child:_action(context,'New Customer',Icons.person_add_alt_1,()=>_addCustomer(context))),Expanded(child:_action(context,'Invoice',Icons.receipt_long,()=>_invoiceList(context))),Expanded(child:_action(context,'Receive',Icons.undo,()=>_receive(context)))]),
      const SizedBox(height:18),Row(children:[const Expanded(child:Text('Recent Rentals',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800))),TextButton(onPressed:()=>_invoiceList(context),child:const Text('Invoices'))]),
      ...data.rentals.reversed.take(5).map((r)=>Card(margin:const EdgeInsets.only(bottom:8),child:ListTile(leading:CircleAvatar(backgroundColor:mint,child:const Icon(Icons.inventory_2,color:teal)),title:Text('${r['customer']} • ${r['item']}',style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text('${r['date']}  •  Qty: ${r['qty']}  •  ${r['days']} day(s)'),trailing:Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.end,children:[Text('₹${(r['amount'] as num).toStringAsFixed(0)}',style:const TextStyle(fontWeight:FontWeight.w800)),Text(r['status']=='issued'?'Issued':'Received',style:TextStyle(color:r['status']=='issued'?teal:Colors.grey))]),onTap:()=>_makeInvoice(context,r))),
      if(data.rentals.isEmpty) const Padding(padding:EdgeInsets.all(30),child:Center(child:Text('No rentals yet'))),
      const SizedBox(height:8),Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:const Color(0xFFFFF0F1),borderRadius:BorderRadius.circular(18)),child:Row(children:[const Icon(Icons.account_balance_wallet_outlined,color:Colors.red),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text("Today's Rental Amount",style:TextStyle(fontWeight:FontWeight.w700)),Text('₹${due.toStringAsFixed(0)}',style:const TextStyle(fontSize:23,fontWeight:FontWeight.w800))]))]))
    ]));
  }
  Widget _stat(String a,String b,IconData i)=>Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(16),boxShadow:[BoxShadow(color:Colors.black.withOpacity(.05),blurRadius:10)]),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(i,color:teal),const Spacer(),Text(a,style:const TextStyle(color:Colors.black54)),Text(b,style:const TextStyle(fontSize:23,fontWeight:FontWeight.w800))]));
  Widget _action(BuildContext c,String t,IconData i,VoidCallback f)=>InkWell(onTap:f,child:Container(margin:const EdgeInsets.all(3),padding:const EdgeInsets.symmetric(vertical:13,horizontal:3),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(14),border:Border.all(color:Colors.black12)),child:Column(children:[Icon(i,color:teal),const SizedBox(height:5),Text(t,style:const TextStyle(fontSize:12,fontWeight:FontWeight.w600))])));
  void _business(BuildContext c)=>showDialog(context:c,builder:(_)=>AlertDialog(title:const Text('RentFlow'),content:const Text('RentFlow\nBy PaliaAPK HUB\nDeveloper by ShanPalia'),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Close'))]));
  Future<void> _addItem(BuildContext c)async{final n=TextEditingController(),cat=TextEditingController(),q=TextEditingController(text:'1'),rate=TextEditingController();String type='Per Day';final ok=await showDialog<bool>(context:c,builder:(_)=>StatefulBuilder(builder:(c,set)=>AlertDialog(title:const Text('Add Item'),content:SingleChildScrollView(child:Column(children:[_field(n,'Item Name'),_field(cat,'Category'),_field(q,'Total Quantity',number:true),_field(rate,'Rent Price',number:true),DropdownButtonFormField(value:type,items:['Per Day','Per Hour','Per Event'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>set(()=>type=v! ),decoration:const InputDecoration(labelText:'Rent Type'))])),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Save'))])));if(ok==true&&n.text.trim().isNotEmpty){data.items.add({'id':data.id(),'name':n.text.trim(),'category':cat.text.trim(),'qty':int.tryParse(q.text)??0,'available':int.tryParse(q.text)??0,'rate':double.tryParse(rate.text)??0,'type':type});await data.save();onChanged();}}
  Future<void> _addCustomer(BuildContext c)async{final n=TextEditingController(),m=TextEditingController(),a=TextEditingController();final ok=await showDialog<bool>(context:c,builder:(_)=>AlertDialog(title:const Text('New Customer'),content:Column(mainAxisSize:MainAxisSize.min,children:[_field(n,'Customer Name'),_field(m,'Mobile'),_field(a,'Address')]),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Save'))]));if(ok==true&&n.text.trim().isNotEmpty){data.customers.add({'id':data.id(),'name':n.text.trim(),'mobile':m.text.trim(),'address':a.text.trim()});await data.save();onChanged();}}
  Future<void> _rental(BuildContext c)async{if(data.customers.isEmpty||data.items.isEmpty){ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Please add at least one customer and one item first.')));return;}String customer=data.customers.first['name'],item=data.items.first['name'];final q=TextEditingController(text:'1'),days=TextEditingController(text:'1'),rate=TextEditingController(text:'${data.items.first['rate']}');final ok=await showDialog<bool>(context:c,builder:(_)=>StatefulBuilder(builder:(c,set)=>AlertDialog(title:const Text('New Rental'),content:SingleChildScrollView(child:Column(children:[DropdownButtonFormField(value:customer,items:data.customers.map((x)=>DropdownMenuItem(value:x['name'] as String,child:Text(x['name']))).toList(),onChanged:(v)=>set(()=>customer=v!),decoration:const InputDecoration(labelText:'Customer')),DropdownButtonFormField(value:item,items:data.items.map((x)=>DropdownMenuItem(value:x['name'] as String,child:Text(x['name']))).toList(),onChanged:(v){set((){item=v!;rate.text='${data.items.firstWhere((x)=>x['name']==item)['rate']}';});},decoration:const InputDecoration(labelText:'Item')),_field(q,'Quantity',number:true),_field(days,'Days',number:true),_field(rate,'Rate (manual edit allowed)',number:true)])),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Create'))])));if(ok==true){final it=data.items.firstWhere((x)=>x['name']==item);final qty=int.tryParse(q.text)??0;if(qty>(it['available']??0)){ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Not enough available quantity.')));return;}final amt=qty*(double.tryParse(rate.text)??0)*(int.tryParse(days.text)??1);it['available']=(it['available'] as int)-qty;final r={'id':data.id(),'date':_date(),'customer':customer,'item':item,'qty':qty,'days':int.tryParse(days.text)??1,'rate':double.tryParse(rate.text)??0,'amount':amt,'status':'issued'};data.rentals.add(r);data.invoices.add({...r,'invoice':'INV-${data.invoices.length+1}'});await data.save();onChanged();}}
  Future<void> _receive(BuildContext c)async{final active=data.rentals.where((x)=>x['status']=='issued').toList();if(active.isEmpty){ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('No issued items found.')));return;}String id=active.first['id'];final q=TextEditingController(text:'${active.first['qty']}');final ok=await showDialog<bool>(context:c,builder:(_)=>StatefulBuilder(builder:(c,set)=>AlertDialog(title:const Text('Receive Item'),content:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField(value:id,items:active.map((x)=>DropdownMenuItem(value:x['id'] as String,child:Text('${x['customer']} • ${x['item']}'))).toList(),onChanged:(v)=>set(()=>id=v!),decoration:const InputDecoration(labelText:'Rental')), _field(q,'Received Quantity',number:true)]),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Receive'))])));if(ok==true){final r=data.rentals.firstWhere((x)=>x['id']==id);final got=int.tryParse(q.text)??0;final it=data.items.firstWhere((x)=>x['name']==r['item']);it['available']=(it['available'] as int)+got;if(got>=(r['qty'] as int)){r['status']='received';}else{r['qty']=(r['qty'] as int)-got;}await data.save();onChanged();}}
  void _invoiceList(BuildContext c)=>showModalBottomSheet(context:c,isScrollControlled:true,builder:(_)=>DraggableScrollableSheet(expand:false,builder:(_,sc)=>ListView(padding:const EdgeInsets.all(18),controller:sc,children:[const Text('Invoices',style:TextStyle(fontSize:24,fontWeight:FontWeight.w800)),...data.invoices.reversed.map((i)=>ListTile(title:Text(i['invoice'],style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text('${i['customer']} • ${i['item']} • ${i['date']}'),trailing:Text('₹${(i['amount'] as num).toStringAsFixed(0)}'),onTap:()=>_makeInvoice(c,i)))])));
  Future<void> _makeInvoice(BuildContext c,Map<String,dynamic> r)async{final doc=pw.Document();doc.addPage(pw.Page(build:(_)=>pw.Column(crossAxisAlignment:pw.CrossAxisAlignment.start,children:[pw.Text('RENTFLOW',style:pw.TextStyle(fontSize:28,fontWeight:pw.FontWeight.bold)),pw.Text('By PaliaAPK HUB'),pw.Text('Developer by ShanPalia'),pw.SizedBox(height:20),pw.Text('Rental Invoice'),pw.SizedBox(height:12),pw.Text('Invoice: INV-${r['id'].toString().substring(r['id'].toString().length-6)}'),pw.Text('Date: ${r['date']}'),pw.Text('Customer: ${r['customer']}'),pw.SizedBox(height:15),pw.Table.fromTextArray(data:<List<String>>[['Item','Qty','Days','Rate','Amount'],['${r['item']}','${r['qty']}','${r['days']}','₹${r['rate']}','₹${r['amount']}']]]),pw.SizedBox(height:20),pw.Text('TOTAL: ₹${r['amount']}'),pw.SizedBox(height:25),pw.Text('Thank you for your business.') ])));await Printing.layoutPdf(onLayout:(_)=>doc.save());}
}
Widget _field(TextEditingController x,String label,{bool number=false})=>Padding(padding:const EdgeInsets.only(bottom:10),child:TextField(controller:x,keyboardType:number?TextInputType.number:null,decoration:InputDecoration(labelText:label,border:const OutlineInputBorder())));
String _date()=>DateTime.now().toString().split(' ').first.split('-').reversed.join('/');

class ItemsPage extends StatelessWidget {final Store data;final VoidCallback onChanged;const ItemsPage({super.key,required this.data,required this.onChanged});@override Widget build(BuildContext c)=>SafeArea(child:ListView(padding:const EdgeInsets.all(18),children:[Row(children:[const Expanded(child:Text('Items',style:TextStyle(fontSize:28,fontWeight:FontWeight.w800))),FilledButton.icon(onPressed:()=>Home(data:data,onChanged:onChanged)._addItem(c),icon:const Icon(Icons.add),label:const Text('Add'))]),const SizedBox(height:12),...data.items.map((i)=>Card(child:ListTile(leading:CircleAvatar(backgroundColor:mint,child:const Icon(Icons.inventory_2,color:teal)),title:Text(i['name'],style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text('${i['category']} • ${i['type']} • ₹${i['rate']}'),trailing:Text('${i['available']}/${i['qty']}',style:const TextStyle(fontWeight:FontWeight.w800))))),if(data.items.isEmpty)const Padding(padding:EdgeInsets.all(40),child:Center(child:Text('No items added')))]));}

class CustomersPage extends StatelessWidget {final Store data;final VoidCallback onChanged;const CustomersPage({super.key,required this.data,required this.onChanged});@override Widget build(BuildContext c)=>SafeArea(child:ListView(padding:const EdgeInsets.all(18),children:[Row(children:[const Expanded(child:Text('Customers',style:TextStyle(fontSize:28,fontWeight:FontWeight.w800))),FilledButton.icon(onPressed:()=>Home(data:data,onChanged:onChanged)._addCustomer(c),icon:const Icon(Icons.add),label:const Text('Add'))]),const SizedBox(height:12),...data.customers.map((u){final rs=data.rentals.where((r)=>r['customer']==u['name']).toList();final amt=rs.fold<double>(0,(s,r)=>s+(r['amount'] as num));final itemDue=rs.where((r)=>r['status']=='issued').fold<int>(0,(s,r)=>s+(r['qty'] as int));return Card(child:ListTile(leading:CircleAvatar(backgroundColor:mint,child:const Icon(Icons.person,color:teal)),title:Text(u['name'],style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text('${u['mobile']} • ${rs.length} transactions'),trailing:Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.end,children:[Text('₹${amt.toStringAsFixed(0)}',style:const TextStyle(fontWeight:FontWeight.w800)),Text('Item Due: $itemDue',style:const TextStyle(color:Colors.red))]),onTap:()=>_detail(c,u)]));}),if(data.customers.isEmpty)const Padding(padding:EdgeInsets.all(40),child:Center(child:Text('No customers added')))]));}
void _detail(BuildContext c,Map<String,dynamic> u){final rs=data.rentals.where((r)=>r['customer']==u['name']).toList();showModalBottomSheet(context:c,isScrollControlled:true,builder:(_)=>DraggableScrollableSheet(expand:false,builder:(_,sc)=>ListView(controller:sc,padding:const EdgeInsets.all(18),children:[Text(u['name'],style:const TextStyle(fontSize:26,fontWeight:FontWeight.w800)),Text(u['mobile']),const SizedBox(height:14),const Text('Customer Report',style:TextStyle(fontSize:19,fontWeight:FontWeight.w800)),const SizedBox(height:8),SingleChildScrollView(scrollDirection:Axis.horizontal,child:DataTable(columns:const[DataColumn(label:Text('Date')),DataColumn(label:Text('Item')),DataColumn(label:Text('Issued')),DataColumn(label:Text('Received')),DataColumn(label:Text('Days')),DataColumn(label:Text('Rate')),DataColumn(label:Text('Amount')),DataColumn(label:Text('Due'))],rows:rs.map((r)=>DataRow(cells:[DataCell(Text(r['date'])),DataCell(Text(r['item'])),DataCell(Text('${r['status']=='issued'?r['qty']:r['qty']}')),DataCell(Text(r['status']=='received'?'${r['qty']}':'0')),DataCell(Text('${r['days']}')),DataCell(Text('₹${r['rate']}')),DataCell(Text('₹${r['amount']}')),DataCell(Text(r['status']=='issued'?'₹${r['amount']}':'₹0'))])).toList())]))]));}

class ReportsPage extends StatelessWidget {final Store data;const ReportsPage({super.key,required this.data});@override Widget build(BuildContext c)=>SafeArea(child:ListView(padding:const EdgeInsets.all(18),children:[const Text('Reports',style:TextStyle(fontSize:28,fontWeight:FontWeight.w800)),const SizedBox(height:14),SingleChildScrollView(scrollDirection:Axis.horizontal,child:DataTable(columns:const[DataColumn(label:Text('Date')),DataColumn(label:Text('Customer')),DataColumn(label:Text('Item')),DataColumn(label:Text('Issued')),DataColumn(label:Text('Received')),DataColumn(label:Text('Days')),DataColumn(label:Text('Rate')),DataColumn(label:Text('Amount')),DataColumn(label:Text('Due'))],rows:data.rentals.map((r)=>DataRow(cells:[DataCell(Text(r['date'])),DataCell(Text(r['customer'])),DataCell(Text(r['item'])),DataCell(Text('${r['status']=='issued'?r['qty']:r['qty']}')),DataCell(Text(r['status']=='received'?'${r['qty']}':'0')),DataCell(Text('${r['days']}')),DataCell(Text('₹${r['rate']}')),DataCell(Text('₹${r['amount']}')),DataCell(Text(r['status']=='issued'?'₹${r['amount']}':'₹0'))])).toList())]),if(data.rentals.isEmpty)const Padding(padding:EdgeInsets.all(40),child:Center(child:Text('No report data yet')))]));}
