import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:http/http.dart' as http;

const primary = Color(0xFF00A889);
const primaryDark = Color(0xFF087864);
const dark = Color(0xFF10241F);
const bg = Color(0xFFF5FAF8);
const line = Color(0xFFDDEBE6);
const soft = Color(0xFFE7F7F2);

String uid() => DateTime.now().microsecondsSinceEpoch.toString();
String today() => DateTime.now().toIso8601String().substring(0, 10);

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const RentFlowApp());
}

class Store extends ChangeNotifier {
  late SharedPreferences prefs;
  List<Map<String, dynamic>> shops = [];
  int active = 0;
  bool get registered => shops.isNotEmpty;
  Map<String, dynamic> get shop => registered ? shops[active] : <String, dynamic>{};
  List<Map<String, dynamic>> list(String key) {
    final v = shop[key];
    if (v is! List) return [];
    return v.whereType<Map>().map((e) => Map<String, dynamic>.from(e)).toList();
  }
  List<Map<String, dynamic>> get items => list('items');
  List<Map<String, dynamic>> get customers => list('customers');
  List<Map<String, dynamic>> get issued => list('issued');
  List<Map<String, dynamic>> get returns => list('returns');
  Future<void> load() async {
    prefs = await SharedPreferences.getInstance();
    try {
      final raw = jsonDecode(prefs.getString('shops') ?? '[]');
      if (raw is List) shops = raw.whereType<Map>().map((e) => Map<String, dynamic>.from(e)).toList();
    } catch (_) { shops = []; }
    active = prefs.getInt('active') ?? 0;
    if (active >= shops.length) active = shops.isEmpty ? 0 : shops.length - 1;
  }
  Map<String, dynamic> newShop(String name, String owner, String mobile, String address) => {
    'id': uid(), 'name': name.trim(), 'owner': owner.trim(), 'mobile': mobile.trim(), 'address': address.trim(),
    'items': <Map<String, dynamic>>[], 'customers': <Map<String, dynamic>>[],
    'issued': <Map<String, dynamic>>[], 'returns': <Map<String, dynamic>>[],
  };
  Future<void> save() async {
    await prefs.setString('shops', jsonEncode(shops));
    await prefs.setInt('active', active);
    notifyListeners();
  }
  Future<void> addShop(String n, String o, String m, String a) async { shops.add(newShop(n,o,m,a)); active=shops.length-1; await save(); }
  Future<void> updateShop(String n, String o, String m, String a) async { if(!registered)return; shop['name']=n;shop['owner']=o;shop['mobile']=m;shop['address']=a;await save(); }
  Future<void> deleteShop(int i) async { if(i<0||i>=shops.length)return; shops.removeAt(i); active=shops.isEmpty?0:active.clamp(0,shops.length-1).toInt(); await save(); }
  Future<void> selectShop(int i) async { if(i<0||i>=shops.length)return; active=i; await save(); }
  Future<void> addRecord(String key, Map<String,dynamic> value) async { (shop[key] as List).add(value); await save(); }
  Future<void> updateRecord(String key, int index, Map<String,dynamic> value) async { (shop[key] as List)[index]=value; await save(); }
  Future<void> deleteRecord(String key, int index) async { (shop[key] as List).removeAt(index); await save(); }
}

class RentFlowApp extends StatelessWidget {
  const RentFlowApp({super.key});
  @override Widget build(BuildContext context) => MaterialApp(
    debugShowCheckedModeBanner: false, title: 'RentFlow',
    theme: ThemeData(useMaterial3: true, scaffoldBackgroundColor: bg, colorScheme: ColorScheme.fromSeed(seedColor: primary),
      inputDecorationTheme: InputDecorationTheme(filled: true, fillColor: Colors.white, labelStyle: const TextStyle(color: Colors.black54),
        contentPadding: const EdgeInsets.symmetric(horizontal: 18, vertical: 17),
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(17), borderSide: const BorderSide(color: line)),
        enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(17), borderSide: const BorderSide(color: line)),
        focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(17), borderSide: const BorderSide(color: primary, width: 1.8)))),
    home: const SplashPage(),
  );
}

class SplashPage extends StatefulWidget { const SplashPage({super.key}); @override State<SplashPage> createState()=>_SplashPageState(); }
class _SplashPageState extends State<SplashPage> {
  @override void initState(){super.initState(); Future.delayed(const Duration(milliseconds:1500),(){if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const AppShell()));});}
  @override Widget build(BuildContext context)=>Scaffold(body:Center(child:Padding(padding:const EdgeInsets.all(22),child:SizedBox(width:350,child:SvgPicture.asset('assets/rentflow_splash.svg')))));
}

class Logo extends StatelessWidget { final double size; const Logo({this.size=46,super.key}); @override Widget build(BuildContext context)=>SvgPicture.asset('assets/rentflow_logo.svg',width:size,height:size); }

class AppHeader extends StatelessWidget implements PreferredSizeWidget {
  final bool back; final List<Widget> actions;
  const AppHeader({this.back=false,this.actions=const [],super.key});
  @override Size get preferredSize=>const Size.fromHeight(72);
  @override Widget build(BuildContext context)=>AppBar(
    backgroundColor:bg,surfaceTintColor:Colors.transparent,elevation:0,toolbarHeight:72,automaticallyImplyLeading:false,
    leadingWidth: back ? 98 : 58,
    leading: back ? Row(children:[IconButton(onPressed:()=>Navigator.maybePop(context),icon:const Icon(Icons.arrow_back,color:dark)),const Logo(size:36)]) : const Padding(padding:EdgeInsets.only(left:10),child:Logo(size:42)),
    titleSpacing:4,
    title: const Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.center,children:[Text('RentFlow',style:TextStyle(color:dark,fontSize:21,fontWeight:FontWeight.w900)),Text('By PaliaAPK HUB',style:TextStyle(color:primary,fontSize:12,fontWeight:FontWeight.w800))]),
    actions: actions,
  );
}

class AppShell extends StatefulWidget { const AppShell({super.key}); @override State<AppShell> createState()=>_AppShellState(); }
class _AppShellState extends State<AppShell> {
  final store=Store(); int tab=0; bool loading=true;
  @override void initState(){super.initState();store.load().then((_){if(mounted)setState(()=>loading=false);});}
  Future<bool> gate() async { if(store.registered)return true; await Navigator.push(context,MaterialPageRoute(builder:(_)=>ShopFormPage(store:store))); return store.registered; }
  @override Widget build(BuildContext context){
    if(loading)return const Scaffold(body:Center(child:CircularProgressIndicator(color:primary)));
    final pages=[HomePage(store:store,gate:gate),ItemsPage(store:store,gate:gate),CustomersPage(store:store,gate:gate),IssuedPage(store:store,gate:gate),SettingsPage(store:store)];
    return AnimatedBuilder(animation:store,builder:(_,__)=>Scaffold(body:pages[tab],bottomNavigationBar:NavigationBar(height:78,backgroundColor:const Color(0xFFEAF2EF),indicatorColor:const Color(0xFFCDEEE4),selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[
      NavigationDestination(icon:Icon(Icons.grid_view_outlined),selectedIcon:Icon(Icons.grid_view_rounded),label:'Home'),
      NavigationDestination(icon:Icon(Icons.inventory_2_outlined),selectedIcon:Icon(Icons.inventory_2_rounded),label:'Items'),
      NavigationDestination(icon:Icon(Icons.people_outline),selectedIcon:Icon(Icons.people_rounded),label:'Customers'),
      NavigationDestination(icon:Icon(Icons.assignment_outlined),selectedIcon:Icon(Icons.assignment_rounded),label:'Issued'),
      NavigationDestination(icon:Icon(Icons.settings_outlined),selectedIcon:Icon(Icons.settings_rounded),label:'Settings'),
    ])));
  }
}

class Page extends StatelessWidget { final String title; final Widget child; final List<Widget> actions; const Page({required this.title,required this.child,this.actions=const[],super.key}); @override Widget build(BuildContext context)=>Scaffold(appBar:AppHeader(actions:actions),body:ListView(padding:const EdgeInsets.fromLTRB(18,8,18,34),children:[Text(title,style:const TextStyle(color:dark,fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:16),child])); }
class SectionCard extends StatelessWidget { final Widget child; const SectionCard({required this.child,super.key}); @override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(22),border:Border.all(color:line)),child:child); }
class StatCard extends StatelessWidget { final String value,label; final IconData icon; const StatCard({required this.value,required this.label,required this.icon,super.key}); @override Widget build(BuildContext context)=>Expanded(child:SectionCard(child:Row(children:[Container(padding:const EdgeInsets.all(11),decoration:BoxDecoration(color:soft,borderRadius:BorderRadius.circular(15)),child:Icon(icon,color:primary,size:25)),const SizedBox(width:10),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(value,style:const TextStyle(color:dark,fontSize:22,fontWeight:FontWeight.w900)),Text(label,style:const TextStyle(color:Colors.black54))])]))); }

class HomePage extends StatelessWidget {
  final Store store; final Future<bool> Function() gate; const HomePage({required this.store,required this.gate,super.key});
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:bg,appBar:const AppHeader(),body:SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(18,16,18,30),children:[
    if(!store.registered) SectionCard(child:Row(children:[const Logo(size:52),const SizedBox(width:12),const Expanded(child:Text('Register your shop to start managing rentals.',style:TextStyle(color:dark,fontWeight:FontWeight.w800))),FilledButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>ShopFormPage(store:store))),child:const Text('Register'))])) else _ShopSummary(store:store),
    const SizedBox(height:14),Row(children:[StatCard(value:'${store.items.length}',label:'Items',icon:Icons.inventory_2_outlined),const SizedBox(width:10),StatCard(value:'${store.customers.length}',label:'Customers',icon:Icons.people_outline)]),
    const SizedBox(height:10),Row(children:[StatCard(value:'${store.issued.length}',label:'Issued',icon:Icons.assignment_outlined),const SizedBox(width:10),StatCard(value:'${store.returns.length}',label:'Returns',icon:Icons.keyboard_return)]),
    const SizedBox(height:24),const Text('Quick actions',style:TextStyle(color:dark,fontSize:24,fontWeight:FontWeight.w900)),const SizedBox(height:11),
    Row(children:[Expanded(child:_Action(label:'Add Item',icon:Icons.add_box_outlined,onTap:()async{if(await gate()&&context.mounted)Navigator.push(context,MaterialPageRoute(builder:(_)=>ItemFormPage(store:store)));})),const SizedBox(width:10),Expanded(child:_Action(label:'Customer',icon:Icons.person_add_alt_1_outlined,onTap:()async{if(await gate()&&context.mounted)Navigator.push(context,MaterialPageRoute(builder:(_)=>CustomerFormPage(store:store)));}))]),
    const SizedBox(height:10),Row(children:[Expanded(child:_Action(label:'Issued',icon:Icons.assignment_outlined,onTap:()async{if(await gate()&&context.mounted)Navigator.push(context,MaterialPageRoute(builder:(_)=>IssueFormPage(store:store)));})),const SizedBox(width:10),Expanded(child:_Action(label:'Return',icon:Icons.keyboard_return_rounded,onTap:()async{if(await gate()&&context.mounted)Navigator.push(context,MaterialPageRoute(builder:(_)=>ReturnFormPage(store:store)));}))]),
    const SizedBox(height:24),const Text('Recent issued',style:TextStyle(color:dark,fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:10),
    if(store.issued.isEmpty) const SectionCard(child:Column(children:[Icon(Icons.receipt_long_outlined,color:primary,size:44),SizedBox(height:8),Text('No issued entries',style:TextStyle(color:dark,fontSize:17,fontWeight:FontWeight.w900)),SizedBox(height:4),Text('Your saved invoices will appear here.',textAlign:TextAlign.center,style:TextStyle(color:Colors.black54))])) else ...store.issued.reversed.take(5).map((e)=>_EntryCard(data:e)),
    const SizedBox(height:20),const Center(child:Column(children:[Text('RentFlow',style:TextStyle(color:dark,fontSize:16,fontWeight:FontWeight.w900)),Text('By PaliaAPK HUB',style:TextStyle(color:primary,fontSize:12,fontWeight:FontWeight.w800)),Text('Developer by ShanPalia',style:TextStyle(color:Colors.black45,fontSize:11))]))
  ])));
}
class _ShopSummary extends StatelessWidget { final Store store; const _ShopSummary({required this.store}); @override Widget build(BuildContext context){final s=store.shop;return SectionCard(child:Row(children:[const Logo(size:50),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${s['name']}',style:const TextStyle(color:dark,fontSize:19,fontWeight:FontWeight.w900)),Text('${s['owner']}  •  ${s['mobile']}',style:const TextStyle(color:Colors.black54)),Text('${s['address']}',maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.black54))])),IconButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>ShopManagerPage(store:store))),icon:const Icon(Icons.edit_outlined,color:primary))]));}}
class _Action extends StatelessWidget { final String label; final IconData icon; final VoidCallback onTap; const _Action({required this.label,required this.icon,required this.onTap}); @override Widget build(BuildContext context)=>InkWell(onTap:onTap,borderRadius:BorderRadius.circular(20),child:SectionCard(child:Column(children:[Container(padding:const EdgeInsets.all(11),decoration:BoxDecoration(color:soft,borderRadius:BorderRadius.circular(15)),child:Icon(icon,color:primary,size:28)),const SizedBox(height:7),Text(label,style:const TextStyle(color:dark,fontWeight:FontWeight.w900))])));}
class _EntryCard extends StatelessWidget { final Map<String,dynamic> data; const _EntryCard({required this.data}); @override Widget build(BuildContext context)=>Container(margin:const EdgeInsets.only(bottom:9),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18),border:Border.all(color:line)),child:Row(children:[Container(padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:soft,borderRadius:BorderRadius.circular(13)),child:const Icon(Icons.receipt_long_outlined,color:primary)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${data['invoice']??'Invoice'}',style:const TextStyle(color:dark,fontWeight:FontWeight.w900)),Text('${data['customerName']??''}',style:const TextStyle(color:Colors.black54)),Text('${data['date']??''}',style:const TextStyle(color:Colors.black45,fontSize:12))]))])); }

class ItemsPage extends StatelessWidget { final Store store; final Future<bool> Function() gate; const ItemsPage({required this.store,required this.gate,super.key}); @override Widget build(BuildContext context)=>Page(title:'Items',actions:[IconButton(onPressed:()async{if(await gate()&&context.mounted)Navigator.push(context,MaterialPageRoute(builder:(_)=>ItemFormPage(store:store)));},icon:const Icon(Icons.add_circle_outline,color:primary))],child:Column(children:[if(store.items.isEmpty)const SectionCard(child:Text('No items yet. Add your first rental item.',style:TextStyle(color:Colors.black54))) else ...store.items.asMap().entries.map((e)=>_ListTile(title:'${e.value['name']}',subtitle:'Quantity: ${e.value['quantity']}',icon:Icons.inventory_2_outlined,onEdit:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>ItemFormPage(store:store,index:e.key))),onDelete:()=>confirmDelete(context,()=>store.deleteRecord('items',e.key))))]));}
class CustomersPage extends StatelessWidget { final Store store; final Future<bool> Function() gate; const CustomersPage({required this.store,required this.gate,super.key}); @override Widget build(BuildContext context)=>Page(title:'Customers',actions:[IconButton(onPressed:()async{if(await gate()&&context.mounted)Navigator.push(context,MaterialPageRoute(builder:(_)=>CustomerFormPage(store:store)));},icon:const Icon(Icons.person_add_alt_1_outlined,color:primary))],child:Column(children:[if(store.customers.isEmpty)const SectionCard(child:Text('No customers yet.',style:TextStyle(color:Colors.black54))) else ...store.customers.asMap().entries.map((e)=>_ListTile(title:'${e.value['name']}',subtitle:'${e.value['mobile']}  •  ${e.value['address']}',icon:Icons.person_outline,onEdit:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>CustomerFormPage(store:store,index:e.key))),onDelete:()=>confirmDelete(context,()=>store.deleteRecord('customers',e.key))))]));}
class IssuedPage extends StatelessWidget { final Store store; final Future<bool> Function() gate; const IssuedPage({required this.store,required this.gate,super.key}); @override Widget build(BuildContext context)=>Page(title:'Issued',actions:[IconButton(onPressed:()async{if(await gate()&&context.mounted)Navigator.push(context,MaterialPageRoute(builder:(_)=>IssueFormPage(store:store)));},icon:const Icon(Icons.add_circle_outline,color:primary))],child:Column(children:[if(store.issued.isEmpty)const SectionCard(child:Text('No issued invoices yet.',style:TextStyle(color:Colors.black54))) else ...store.issued.asMap().entries.map((e)=>_ListTile(title:'${e.value['invoice']}',subtitle:'${e.value['customerName']}  •  ${e.value['date']}',icon:Icons.receipt_long_outlined,onDelete:()=>confirmDelete(context,()=>store.deleteRecord('issued',e.key))))]));}
class _ListTile extends StatelessWidget { final String title,subtitle; final IconData icon; final VoidCallback? onEdit,onDelete; const _ListTile({required this.title,required this.subtitle,required this.icon,this.onEdit,this.onDelete}); @override Widget build(BuildContext context)=>Container(margin:const EdgeInsets.only(bottom:9),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18),border:Border.all(color:line)),child:Row(children:[Container(padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:soft,borderRadius:BorderRadius.circular(13)),child:Icon(icon,color:primary)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:dark,fontWeight:FontWeight.w900)),Text(subtitle,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.black54))])),if(onEdit!=null)IconButton(onPressed:onEdit,icon:const Icon(Icons.edit_outlined,color:primary)),if(onDelete!=null)IconButton(onPressed:onDelete,icon:const Icon(Icons.delete_outline,color:Colors.redAccent))])); }

class SettingsPage extends StatelessWidget { final Store store; const SettingsPage({required this.store,super.key}); @override Widget build(BuildContext context)=>Page(title:'Settings',child:Column(children:[SectionCard(child:Column(children:[const Row(children:[Icon(Icons.store_outlined,color:primary),SizedBox(width:10),Text('Shop management',style:TextStyle(color:dark,fontSize:17,fontWeight:FontWeight.w900))]),const SizedBox(height:10),const Text('Edit, delete or add another shop/address from Shop Management.',style:TextStyle(color:Colors.black54))])),const SizedBox(height:10),FilledButton.icon(style:FilledButton.styleFrom(minimumSize:const Size.fromHeight(52),backgroundColor:primaryDark),onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>ShopManagerPage(store:store))),icon:const Icon(Icons.store_mall_directory_outlined),label:const Text('Open Shop Management')),const SizedBox(height:10),OutlinedButton.icon(style:OutlinedButton.styleFrom(minimumSize:const Size.fromHeight(52)),onPressed:()=>checkUpdate(context),icon:const Icon(Icons.system_update_outlined,color:primary),label:const Text('Check for updates')),const SizedBox(height:24),const Center(child:Text('RentFlow  •  By PaliaAPK HUB\nDeveloper by ShanPalia',textAlign:TextAlign.center,style:TextStyle(color:Colors.black45,fontSize:12))) ])); }

class ShopManagerPage extends StatelessWidget { final Store store; const ShopManagerPage({required this.store,super.key}); @override Widget build(BuildContext context)=>Page(title:'Shop Management',actions:[IconButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>ShopFormPage(store:store))),icon:const Icon(Icons.add_business_outlined,color:primary))],child:Column(children:[...store.shops.asMap().entries.map((e){final s=e.value;return Container(margin:const EdgeInsets.only(bottom:10),padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(19),border:Border.all(color:e.key==store.active?primary:line,width:e.key==store.active?1.6:1)),child:Row(children:[const Logo(size:44),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${s['name']}',style:const TextStyle(color:dark,fontSize:17,fontWeight:FontWeight.w900)),Text('${s['owner']}  •  ${s['mobile']}',style:const TextStyle(color:Colors.black54)),Text('${s['address']}',maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.black54))])),IconButton(onPressed:()=>store.selectShop(e.key),icon:Icon(e.key==store.active?Icons.check_circle:Icons.radio_button_unchecked,color:primary)),IconButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>ShopFormPage(store:store,index:e.key))),icon:const Icon(Icons.edit_outlined,color:primary)),IconButton(onPressed:()=>confirmDelete(context,()=>store.deleteShop(e.key)),icon:const Icon(Icons.delete_outline,color:Colors.redAccent))]));})])); }

class ShopFormPage extends StatefulWidget { final Store store; final int? index; const ShopFormPage({required this.store,this.index,super.key}); @override State<ShopFormPage> createState()=>_ShopFormPageState(); }
class _ShopFormPageState extends State<ShopFormPage>{late TextEditingController n,o,m,a;@override void initState(){super.initState();final s=widget.index==null?null:widget.store.shops[widget.index!];n=TextEditingController(text:'${s?['name']??''}');o=TextEditingController(text:'${s?['owner']??''}');m=TextEditingController(text:'${s?['mobile']??''}');a=TextEditingController(text:'${s?['address']??''}');}@override void dispose(){n.dispose();o.dispose();m.dispose();a.dispose();super.dispose();}@override Widget build(BuildContext context)=>_FormScaffold(title:widget.index==null?'Add New Shop':'Edit Shop',children:[Field(c:'Shop name',controller:n),Field(c:'Shop owner',controller:o),Field(c:'Mobile number',controller:m,k:TextInputType.phone),Field(c:'Shop address',controller:a,max:3),FilledButton.icon(style:FilledButton.styleFrom(minimumSize:const Size.fromHeight(54),backgroundColor:primaryDark),onPressed:()async{if(n.text.trim().isEmpty)return;if(widget.index==null)await widget.store.addShop(n.text,o.text,m.text,a.text);else await widget.store.updateShop(n.text,o.text,m.text,a.text);if(context.mounted)Navigator.pop(context);},icon:Icon(widget.index==null?Icons.add_business_outlined:Icons.save_outlined),label:Text(widget.index==null?'Create Shop':'Save Changes'))]);}

class ItemFormPage extends StatefulWidget { final Store store; final int? index; const ItemFormPage({required this.store,this.index,super.key}); @override State<ItemFormPage> createState()=>_ItemFormPageState(); }
class _ItemFormPageState extends State<ItemFormPage>{late TextEditingController n,q,d;@override void initState(){super.initState();final x=widget.index==null?null:widget.store.items[widget.index!];n=TextEditingController(text:'${x?['name']??''}');q=TextEditingController(text:'${x?['quantity']??'1'}');d=TextEditingController(text:'${x?['note']??''}');}@override void dispose(){n.dispose();q.dispose();d.dispose();super.dispose();}@override Widget build(BuildContext context)=>_FormScaffold(title:widget.index==null?'Add Item':'Edit Item',children:[Field(c:'Item name',controller:n),Field(c:'Total quantity',controller:q,k:TextInputType.number),Field(c:'Note (optional)',controller:d,max:3),FilledButton.icon(style:FilledButton.styleFrom(minimumSize:const Size.fromHeight(54),backgroundColor:primaryDark),onPressed:()async{final value={'id':widget.index==null?uid():'${widget.store.items[widget.index!]['id']}','name':n.text.trim(),'quantity':int.tryParse(q.text.trim())??0,'note':d.text.trim()};if(widget.index==null)await widget.store.addRecord('items',value);else await widget.store.updateRecord('items',widget.index!,value);if(context.mounted)Navigator.pop(context);},icon:const Icon(Icons.save_outlined),label:const Text('Save Item'))]);}

class CustomerFormPage extends StatefulWidget { final Store store; final int? index; const CustomerFormPage({required this.store,this.index,super.key}); @override State<CustomerFormPage> createState()=>_CustomerFormPageState(); }
class _CustomerFormPageState extends State<CustomerFormPage>{late TextEditingController n,m,a;@override void initState(){super.initState();final x=widget.index==null?null:widget.store.customers[widget.index!];n=TextEditingController(text:'${x?['name']??''}');m=TextEditingController(text:'${x?['mobile']??''}');a=TextEditingController(text:'${x?['address']??''}');}@override void dispose(){n.dispose();m.dispose();a.dispose();super.dispose();}@override Widget build(BuildContext context)=>_FormScaffold(title:widget.index==null?'Add Customer':'Edit Customer',children:[Field(c:'Customer name',controller:n),Field(c:'Mobile number',controller:m,k:TextInputType.phone),Field(c:'Address',controller:a,max:3),FilledButton.icon(style:FilledButton.styleFrom(minimumSize:const Size.fromHeight(54),backgroundColor:primaryDark),onPressed:()async{final v={'id':widget.index==null?uid():'${widget.store.customers[widget.index!]['id']}','name':n.text.trim(),'mobile':m.text.trim(),'address':a.text.trim()};if(widget.index==null)await widget.store.addRecord('customers',v);else await widget.store.updateRecord('customers',widget.index!,v);if(context.mounted)Navigator.pop(context);},icon:const Icon(Icons.save_outlined),label:const Text('Save Customer'))]);}

class IssueFormPage extends StatefulWidget { final Store store; const IssueFormPage({required this.store,super.key}); @override State<IssueFormPage> createState()=>_IssueFormPageState(); }
class _IssueFormPageState extends State<IssueFormPage>{late TextEditingController invoice,date,address;int? customerIndex;List<int> selected=[];@override void initState(){super.initState();invoice=TextEditingController(text:'RF-${DateTime.now().millisecondsSinceEpoch}');date=TextEditingController(text:today());address=TextEditingController();}@override void dispose(){invoice.dispose();date.dispose();address.dispose();super.dispose();}
Future<void> pickCustomer()async{final i=await Navigator.push<int>(context,MaterialPageRoute(builder:(_)=>CustomerPickerPage(store:widget.store)));if(i!=null&&mounted)setState((){customerIndex=i;address.text='${widget.store.customers[i]['address']??''}';});}
Future<void> pickItems()async{final r=await Navigator.push<List<int>>(context,MaterialPageRoute(builder:(_)=>ItemPickerPage(store:widget.store,selected:selected)));if(r!=null&&mounted)setState(()=>selected=r);}
@override Widget build(BuildContext context){final c=customerIndex==null?null:widget.store.customers[customerIndex!];return _FormScaffold(title:'New Issued Entry',children:[Field(c:'Invoice No',controller:invoice),Field(c:'Issued Date',controller:date),InkWell(onTap:pickCustomer,child:InputDecorator(decoration:const InputDecoration(labelText:'Customer'),child:Row(children:[Expanded(child:Text(c==null?'Select customer':'${c['name']}  •  ${c['mobile']}',style:TextStyle(color:c==null?Colors.black54:dark,fontSize:16))),const Icon(Icons.chevron_right)]))),const SizedBox(height:14),Field(c:'Address',controller:address,max:2),const SizedBox(height:4),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('Inventory',style:TextStyle(color:dark,fontSize:22,fontWeight:FontWeight.w900)),FilledButton.icon(onPressed:pickItems,icon:const Icon(Icons.add),label:const Text('Select Items'))]),const SizedBox(height:10),if(selected.isEmpty)const SectionCard(child:Column(children:[Icon(Icons.inventory_2_outlined,color:primary,size:42),SizedBox(height:8),Text('No items selected',style:TextStyle(color:dark,fontWeight:FontWeight.w900)),SizedBox(height:4),Text('Select items on the full inventory page.',textAlign:TextAlign.center,style:TextStyle(color:Colors.black54))])) else ...selected.map((i)=>SectionCard(child:Row(children:[const Icon(Icons.inventory_2_outlined,color:primary),const SizedBox(width:10),Expanded(child:Text('${widget.store.items[i]['name']}  ×  ${widget.store.items[i]['quantity']}',style:const TextStyle(color:dark,fontWeight:FontWeight.w700)))]))),const SizedBox(height:16),FilledButton.icon(style:FilledButton.styleFrom(minimumSize:const Size.fromHeight(54),backgroundColor:primaryDark),onPressed:()async{if(customerIndex==null||selected.isEmpty)return;final v={'id':uid(),'invoice':invoice.text.trim(),'date':date.text.trim(),'customerId':'${c['id']}','customerName':'${c['name']}','customerMobile':'${c['mobile']}','address':address.text.trim(),'items':selected.map((i)=>{'id':widget.store.items[i]['id'],'name':widget.store.items[i]['name'],'quantity':widget.store.items[i]['quantity']}).toList()};await widget.store.addRecord('issued',v);if(context.mounted)Navigator.pop(context);},icon:const Icon(Icons.save_outlined),label:const Text('Save Issued Entry'))]);}}

class CustomerPickerPage extends StatelessWidget { final Store store; const CustomerPickerPage({required this.store,super.key});@override Widget build(BuildContext context)=>Page(title:'Select Customer',child:Column(children:[if(store.customers.isEmpty)const SectionCard(child:Text('No customers available. Add a customer first.',style:TextStyle(color:Colors.black54))) else ...store.customers.asMap().entries.map((e)=>InkWell(onTap:()=>Navigator.pop(context,e.key),borderRadius:BorderRadius.circular(18),child:Container(margin:const EdgeInsets.only(bottom:9),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18),border:Border.all(color:line)),child:Row(children:[Container(padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:soft,borderRadius:BorderRadius.circular(13)),child:const Icon(Icons.person_outline,color:primary)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${e.value['name']}',style:const TextStyle(color:dark,fontWeight:FontWeight.w900)),Text('${e.value['mobile']}  •  ${e.value['address']}',maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.black54))])),const Icon(Icons.chevron_right)])))]));}

class ItemPickerPage extends StatefulWidget { final Store store; final List<int> selected; const ItemPickerPage({required this.store,required this.selected,super.key}); @override State<ItemPickerPage> createState()=>_ItemPickerPageState(); }
class _ItemPickerPageState extends State<ItemPickerPage>{late Set<int> selected;@override void initState(){super.initState();selected=widget.selected.toSet();}@override Widget build(BuildContext context)=>Page(title:'Select Inventory',actions:[TextButton(onPressed:()=>Navigator.pop(context,selected.toList()),child:const Text('Done'))],child:Column(children:[if(widget.store.items.isEmpty)const SectionCard(child:Text('No inventory items available.',style:TextStyle(color:Colors.black54))) else ...widget.store.items.asMap().entries.map((e){final yes=selected.contains(e.key);return InkWell(onTap:()=>setState((){if(yes){selected.remove(e.key);}else{selected.add(e.key);}}),borderRadius:BorderRadius.circular(18),child:Container(margin:const EdgeInsets.only(bottom:9),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18),border:Border.all(color:yes?primary:line,width:yes?1.7:1)),child:Row(children:[Container(padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:soft,borderRadius:BorderRadius.circular(13)),child:Icon(yes?Icons.check_rounded:Icons.inventory_2_outlined,color:primary)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${e.value['name']}',style:const TextStyle(color:dark,fontWeight:FontWeight.w900)),Text('Quantity: ${e.value['quantity']}',style:const TextStyle(color:Colors.black54))])),if(yes)const Icon(Icons.check_circle,color:primary)]));})]));}

class ReturnFormPage extends StatefulWidget { final Store store; const ReturnFormPage({required this.store,super.key}); @override State<ReturnFormPage> createState()=>_ReturnFormPageState(); }
class _ReturnFormPageState extends State<ReturnFormPage>{int? issueIndex;late TextEditingController date,amount,qty,note;@override void initState(){super.initState();date=TextEditingController(text:today());amount=TextEditingController();qty=TextEditingController(text:'1');note=TextEditingController();}@override void dispose(){date.dispose();amount.dispose();qty.dispose();note.dispose();super.dispose();}
Future<void> pickIssue()async{final i=await Navigator.push<int>(context,MaterialPageRoute(builder:(_)=>IssuedPickerPage(store:widget.store)));if(i!=null&&mounted)setState(()=>issueIndex=i);}
@override Widget build(BuildContext context){final x=issueIndex==null?null:widget.store.issued[issueIndex!];return _FormScaffold(title:'Return Entry',children:[InkWell(onTap:pickIssue,child:InputDecorator(decoration:const InputDecoration(labelText:'Issued Invoice'),child:Row(children:[Expanded(child:Text(x==null?'Select issued invoice':'${x['invoice']}  •  ${x['customerName']}',style:TextStyle(color:x==null?Colors.black54:dark,fontSize:16))),const Icon(Icons.chevron_right)]))),const SizedBox(height:14),Field(c:'Return Date',controller:date),Field(c:'Return Amount (manual)',controller:amount,k:const TextInputType.numberWithOptions(decimal:true)),Field(c:'Returned Quantity',controller:qty,k:TextInputType.number),Field(c:'Notes (optional)',controller:note,max:3),const SizedBox(height:8),FilledButton.icon(style:FilledButton.styleFrom(minimumSize:const Size.fromHeight(54),backgroundColor:primaryDark),onPressed:()async{if(x==null)return;final v={'id':uid(),'date':date.text.trim(),'invoice':'${x['invoice']}','customerName':'${x['customerName']}','amount':amount.text.trim(),'quantity':int.tryParse(qty.text.trim())??0,'note':note.text.trim()};await widget.store.addRecord('returns',v);if(context.mounted)Navigator.pop(context);},icon:const Icon(Icons.keyboard_return),label:const Text('Save Return'))]);}}

class IssuedPickerPage extends StatelessWidget { final Store store; const IssuedPickerPage({required this.store,super.key}); @override Widget build(BuildContext context)=>Page(title:'Select Issued Invoice',child:Column(children:[if(store.issued.isEmpty)const SectionCard(child:Text('No issued invoices available.',style:TextStyle(color:Colors.black54))) else ...store.issued.asMap().entries.map((e)=>InkWell(onTap:()=>Navigator.pop(context,e.key),borderRadius:BorderRadius.circular(18),child:Container(margin:const EdgeInsets.only(bottom:9),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18),border:Border.all(color:line)),child:Row(children:[const Icon(Icons.receipt_long_outlined,color:primary,size:30),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${e.value['invoice']}',style:const TextStyle(color:dark,fontWeight:FontWeight.w900)),Text('${e.value['customerName']}  •  ${e.value['date']}',style:const TextStyle(color:Colors.black54))])),const Icon(Icons.chevron_right)])))]));}

class _FormScaffold extends StatelessWidget { final String title; final List<Widget> children; const _FormScaffold({required this.title,required this.children}); @override Widget build(BuildContext context)=>Scaffold(appBar:const AppHeader(back:true),body:ListView(padding:const EdgeInsets.fromLTRB(18,8,18,32),children:[Text(title,style:const TextStyle(color:dark,fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:18),...children.map((w)=>Padding(padding:const EdgeInsets.only(bottom:14),child:w))])); }
class Field extends StatelessWidget { final String c; final TextEditingController controller; final TextInputType? k; final int max; const Field({required this.c,required this.controller,this.k,this.max=1}); @override Widget build(BuildContext context)=>TextField(controller:controller,keyboardType:k,maxLines:max,decoration:InputDecoration(labelText:c)); }

Future<void> confirmDelete(BuildContext context,Future<void> Function() action) async {final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Delete?'),content:const Text('This action cannot be undone.'),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Delete'))]))??false;if(ok)await action();}
Future<void> checkUpdate(BuildContext context) async {showDialog(context:context,barrierDismissible:false,builder:(_)=>const Center(child:CircularProgressIndicator(color:primary)));try{final r=await http.get(Uri.parse('https://api.github.com/repos/shanpalia/RentFlow/releases/latest'),headers:{'Accept':'application/vnd.github+json'});if(context.mounted)Navigator.pop(context);if(!context.mounted)return;if(r.statusCode==200){final j=jsonDecode(r.body) as Map<String,dynamic>;final tag='${j['tag_name']??''}';showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('Update Check'),content:Text(tag.isEmpty?'You are using the latest available version.':'Latest RentFlow release: $tag'),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('OK'))]));}else{ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Could not check for updates right now.')));}}catch(_){if(context.mounted)Navigator.pop(context);if(context.mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Update check failed. Please try again.')));}}
