import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:http/http.dart' as http;
import 'package:url_launcher/url_launcher.dart';

const primary = Color(0xFF00A889);
const dark = Color(0xFF10241F);
const bg = Color(0xFFF5FAF8);
const line = Color(0xFFDDEBE6);
const soft = Color(0xFFE7F7F2);

String uid() => DateTime.now().microsecondsSinceEpoch.toString();
String today() => DateTime.now().toIso8601String().substring(0, 10);

Future<void> main() async { WidgetsFlutterBinding.ensureInitialized(); runApp(const RentFlowApp()); }

class Store extends ChangeNotifier {
  late SharedPreferences prefs;
  List<Map<String,dynamic>> shops=[]; int active=0;
  bool get registered=>shops.isNotEmpty;
  Map<String,dynamic> get shop=>registered?shops[active]:<String,dynamic>{};
  List<Map<String,dynamic>> list(String key){final v=shop[key]; if(v is! List)return []; return v.whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList();}
  List<Map<String,dynamic>> get items=>list('items');
  List<Map<String,dynamic>> get customers=>list('customers');
  List<Map<String,dynamic>> get issued=>list('issued');
  List<Map<String,dynamic>> get returns=>list('returns');
  Future<void> load() async { prefs=await SharedPreferences.getInstance(); try{final r=jsonDecode(prefs.getString('shops')??'[]'); if(r is List)shops=r.whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList();}catch(_){shops=[];} active=prefs.getInt('active')??0; if(active>=shops.length)active=shops.isEmpty?0:shops.length-1; }
  Map<String,dynamic> makeShop(String n,String o,String m,String a)=>{'id':uid(),'name':n,'owner':o,'mobile':m,'address':a,'items':<Map<String,dynamic>>[],'customers':<Map<String,dynamic>>[],'issued':<Map<String,dynamic>>[],'returns':<Map<String,dynamic>>[]};
  Future<void> save() async {await prefs.setString('shops',jsonEncode(shops));await prefs.setInt('active',active);notifyListeners();}
  Future<void> addShop(String n,String o,String m,String a)async{shops.add(makeShop(n.trim(),o.trim(),m.trim(),a.trim()));active=shops.length-1;await save();}
  Future<void> updateShop(String n,String o,String m,String a)async{if(!registered)return;shop['name']=n.trim();shop['owner']=o.trim();shop['mobile']=m.trim();shop['address']=a.trim();await save();}
  Future<void> deleteShop(int i)async{if(i<0||i>=shops.length)return;shops.removeAt(i);active=shops.isEmpty?0:active.clamp(0,shops.length-1).toInt();await save();}
  Future<void> selectShop(int i)async{if(i<0||i>=shops.length)return;active=i;await save();}
  Future<void> add(String key,Map<String,dynamic> v)async{(shop[key] as List).add(v);await save();}
  Future<void> update(String key,int i,Map<String,dynamic> v)async{(shop[key] as List)[i]=v;await save();}
  Future<void> remove(String key,int i)async{(shop[key] as List).removeAt(i);await save();}
}

class RentFlowApp extends StatelessWidget {const RentFlowApp({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'RentFlow',theme:ThemeData(useMaterial3:true,scaffoldBackgroundColor:bg,colorScheme:ColorScheme.fromSeed(seedColor:primary),fontFamily:'sans-serif'),home:const SplashPage());}

class SplashPage extends StatefulWidget{const SplashPage({super.key});@override State<SplashPage>createState()=>_SplashState();}
class _SplashState extends State<SplashPage>{@override void initState(){super.initState();Future.delayed(const Duration(milliseconds:1500),(){if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const Shell()));});}@override Widget build(BuildContext c)=>Scaffold(backgroundColor:Colors.white,body:Center(child:Padding(padding:const EdgeInsets.all(20),child:SvgPicture.asset('assets/rentflow_splash.svg',width:360))));}

class Logo extends StatelessWidget{final double size;const Logo({this.size=42,super.key});@override Widget build(BuildContext c)=>SvgPicture.asset('assets/rentflow_logo.svg',width:size,height:size);}
class Header extends StatelessWidget implements PreferredSizeWidget{final bool back;final List<Widget> actions;const Header({this.back=false,this.actions=const[],super.key});@override Size get preferredSize=>const Size.fromHeight(70);@override Widget build(BuildContext c)=>AppBar(backgroundColor:bg,surfaceTintColor:Colors.transparent,elevation:0,toolbarHeight:70,automaticallyImplyLeading:false,leadingWidth:back?58:54,leading:back?IconButton(onPressed:()=>Navigator.pop(c),icon:const Icon(Icons.arrow_back_rounded,color:dark)):const Padding(padding:EdgeInsets.only(left:10),child:Logo(size:40)),title:const Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.center,children:[Text('RentFlow',style:TextStyle(color:dark,fontSize:21,fontWeight:FontWeight.w900)),Text('By PaliaAPK HUB',style:TextStyle(color:primary,fontSize:12,fontWeight:FontWeight.w800))]),actions:actions);}

class Shell extends StatefulWidget{const Shell({super.key});@override State<Shell>createState()=>_ShellState();}
class _ShellState extends State<Shell>{final store=Store();bool loading=true;@override void initState(){super.initState();store.load().then((_){if(mounted)setState(()=>loading=false);});}@override Widget build(BuildContext c){if(loading)return const Scaffold(body:Center(child:CircularProgressIndicator(color:primary)));return AnimatedBuilder(animation:store,builder:(_,__)=>Home(store:store));}}

Future<void> open(BuildContext c,Widget page)=>Navigator.push(c,MaterialPageRoute(builder:(_)=>page));
Future<bool> confirmDelete(BuildContext c)async=>await showDialog<bool>(context:c,builder:(d)=>AlertDialog(title:const Text('Delete entry?'),content:const Text('This action cannot be undone.'),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('Delete'))]))??false;

class Home extends StatelessWidget{final Store store;const Home({required this.store,super.key});@override Widget build(BuildContext c){return Scaffold(appBar:const Header(),body:ListView(padding:const EdgeInsets.fromLTRB(18,10,18,32),children:[
if(!store.registered)Section(child:Row(children:[const Logo(size:50),const SizedBox(width:12),const Expanded(child:Text('Register your shop first to start using RentFlow.',style:TextStyle(color:dark,fontWeight:FontWeight.w700))),FilledButton(onPressed:()=>open(c,ShopForm(store:store)),child:const Text('Register'))])) else ShopStrip(store:store),
const SizedBox(height:22),const Text('Dashboard',style:TextStyle(color:dark,fontSize:29,fontWeight:FontWeight.w900)),const SizedBox(height:4),const Text('Choose what you want to manage',style:TextStyle(color:Colors.black54)),const SizedBox(height:16),
MenuGrid(store:store),const SizedBox(height:24),
Row(children:[MiniStat(value:'${store.items.length}',label:'Items'),const SizedBox(width:10),MiniStat(value:'${store.customers.length}',label:'Customers')]),const SizedBox(height:10),
Row(children:[MiniStat(value:'${store.issued.length}',label:'Issued'),const SizedBox(width:10),MiniStat(value:'${store.returns.length}',label:'Returns')]),const SizedBox(height:26),
const Center(child:Text('RentFlow  •  By PaliaAPK HUB',style:TextStyle(color:primary,fontWeight:FontWeight.w800))) ]));}}

class ShopStrip extends StatelessWidget{final Store store;const ShopStrip({required this.store,super.key});@override Widget build(BuildContext c){final s=store.shop;return Section(child:Row(children:[const Logo(size:48),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${s['name']}',style:const TextStyle(color:dark,fontSize:18,fontWeight:FontWeight.w900)),Text('${s['owner']}  •  ${s['mobile']}',style:const TextStyle(color:Colors.black54)),Text('${s['address']}',maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.black54))])),IconButton(onPressed:()=>open(c,ShopManager(store:store)),icon:const Icon(Icons.edit_outlined,color:primary))]));}}

class MenuGrid extends StatelessWidget{final Store store;const MenuGrid({required this.store,super.key});@override Widget build(BuildContext c){final entries=[['Items','Item master & stock',Icons.inventory_2_outlined,ItemsPage(store:store)],['Customers','Party ledger',Icons.people_outline,CustomersPage(store:store)],['New Issue','Create invoice',Icons.receipt_long_outlined,IssueForm(store:store)],['Returns','Receive & close',Icons.keyboard_return_rounded,ReturnsPage(store:store)],['Shops','Add / edit shops',Icons.storefront_outlined,ShopManager(store:store)],['Settings','Backup & updates',Icons.settings_outlined,SettingsPage(store:store)]];return GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:entries.length,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,crossAxisSpacing:12,mainAxisSpacing:12,childAspectRatio:1.35),itemBuilder:(_,i){final e=entries[i];return InkWell(onTap:()=>open(c,e[3] as Widget),borderRadius:BorderRadius.circular(22),child:Section(child:Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.start,children:[Container(padding:const EdgeInsets.all(11),decoration:BoxDecoration(color:soft,borderRadius:BorderRadius.circular(15)),child:Icon(e[2] as IconData,color:primary,size:28)),const SizedBox(height:10),Text(e[0] as String,style:const TextStyle(color:dark,fontSize:17,fontWeight:FontWeight.w900)),Text(e[1] as String,style:const TextStyle(color:Colors.black54,fontSize:12))])));});}}

class Section extends StatelessWidget{final Widget child;const Section({required this.child,super.key});@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(22),border:Border.all(color:line)),child:child);}
class MiniStat extends StatelessWidget{final String value,label;const MiniStat({required this.value,required this.label,super.key});@override Widget build(BuildContext c)=>Expanded(child:Section(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(value,style:const TextStyle(color:dark,fontSize:25,fontWeight:FontWeight.w900)),Text(label,style:const TextStyle(color:Colors.black54))])));}

class Page extends StatelessWidget{final String title;final Widget child;final List<Widget> actions;const Page({required this.title,required this.child,this.actions=const[],super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:Header(back:true,actions:actions),body:ListView(padding:const EdgeInsets.fromLTRB(18,8,18,30),children:[Text(title,style:const TextStyle(color:dark,fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:16),child]));}

class ItemsPage extends StatelessWidget{final Store store;const ItemsPage({required this.store,super.key});@override Widget build(BuildContext c)=>Page(title:'Items',actions:[IconButton(onPressed:()=>open(c,ItemForm(store:store)),icon:const Icon(Icons.add_circle_outline,color:primary))],child:Column(children:[if(store.items.isEmpty)const Empty(text:'No items yet. Add multiple rental items here.') else ...store.items.asMap().entries.map((e)=>DataRowCard(icon:Icons.inventory_2_outlined,title:'${e.value['name']}',subtitle:'Qty ${e.value['quantity']}  •  Rate ₹${e.value['rate']}',onEdit:()=>open(c,ItemForm(store:store,index:e.key)),onDelete:()async{if(await confirmDelete(c))await store.remove('items',e.key);})),const SizedBox(height:12),FilledButton.icon(onPressed:()=>open(c,ItemForm(store:store)),icon:const Icon(Icons.add),label:const Text('Add another item'))]));}

class ItemForm extends StatefulWidget{final Store store;final int? index;const ItemForm({required this.store,this.index,super.key});@override State<ItemForm>createState()=>_ItemFormState();}
class _ItemFormState extends State<ItemForm>{final name=TextEditingController(),unit=TextEditingController(text:'pcs'),qty=TextEditingController(text:'1'),rate=TextEditingController(text:'0');@override void initState(){super.initState();if(widget.index!=null){final x=widget.store.items[widget.index!];name.text='${x['name']}';unit.text='${x['unit']??'pcs'}';qty.text='${x['quantity']??1}';rate.text='${x['rate']??0}';}}@override Widget build(BuildContext c)=>FormPage(title:widget.index==null?'Add Item':'Edit Item',fields:[FieldBox(label:'Item name',controller:name),Row(children:[Expanded(child:FieldBox(label:'Unit',controller:unit)),const SizedBox(width:10),Expanded(child:FieldBox(label:'Opening quantity',controller:qty,number:true))]),FieldBox(label:'Rental rate',controller:rate,number:true)],onSave:()async{if(name.text.trim().isEmpty)return;final v={'id':widget.index==null?uid():'${widget.store.items[widget.index!]['id']}','name':name.text.trim(),'unit':unit.text.trim(),'quantity':int.tryParse(qty.text)??0,'rate':double.tryParse(rate.text)??0};if(widget.index==null)await widget.store.add('items',v);else await widget.store.update('items',widget.index!,v);if(c.mounted)Navigator.pop(c);});}

class CustomersPage extends StatelessWidget{final Store store;const CustomersPage({required this.store,super.key});@override Widget build(BuildContext c)=>Page(title:'Customers',actions:[IconButton(onPressed:()=>open(c,CustomerForm(store:store)),icon:const Icon(Icons.person_add_alt_1_outlined,color:primary))],child:Column(children:[if(store.customers.isEmpty)const Empty(text:'No customers yet. Add as many parties as you need.') else ...store.customers.asMap().entries.map((e)=>DataRowCard(icon:Icons.person_outline,title:'${e.value['name']}',subtitle:'${e.value['mobile']}  •  ${e.value['address']}',onEdit:()=>open(c,CustomerForm(store:store,index:e.key)),onDelete:()async{if(await confirmDelete(c))await store.remove('customers',e.key);})),const SizedBox(height:12),FilledButton.icon(onPressed:()=>open(c,CustomerForm(store:store)),icon:const Icon(Icons.add),label:const Text('Add another customer'))]));}
class CustomerForm extends StatefulWidget{final Store store;final int? index;const CustomerForm({required this.store,this.index,super.key});@override State<CustomerForm>createState()=>_CustomerFormState();}
class _CustomerFormState extends State<CustomerForm>{final name=TextEditingController(),mobile=TextEditingController(),address=TextEditingController();@override void initState(){super.initState();if(widget.index!=null){final x=widget.store.customers[widget.index!];name.text='${x['name']}';mobile.text='${x['mobile']}';address.text='${x['address']}';}}@override Widget build(BuildContext c)=>FormPage(title:widget.index==null?'Add Customer':'Edit Customer',fields:[FieldBox(label:'Customer / Party name',controller:name),FieldBox(label:'Mobile',controller:mobile,number:true),FieldBox(label:'Address',controller:address,maxLines:3)],onSave:()async{if(name.text.trim().isEmpty)return;final v={'id':widget.index==null?uid():'${widget.store.customers[widget.index!]['id']}','name':name.text.trim(),'mobile':mobile.text.trim(),'address':address.text.trim()};if(widget.index==null)await widget.store.add('customers',v);else await widget.store.update('customers',widget.index!,v);if(c.mounted)Navigator.pop(c);});}

class IssueForm extends StatefulWidget{final Store store;const IssueForm({required this.store,super.key});@override State<IssueForm>createState()=>_IssueState();}
class _IssueState extends State<IssueForm>{final invoice=TextEditingController(text:'RF-${DateTime.now().millisecondsSinceEpoch}'),date=TextEditingController(text:today()),address=TextEditingController();String? customerId;List<Map<String,dynamic>> lines=[];
String customerName(){for(final x in widget.store.customers){if('${x['id']}'==customerId)return '${x['name']}';}return 'Select customer';}
Future<void> chooseCustomer()async{final r=await Navigator.push<Map<String,dynamic>>(context,MaterialPageRoute(builder:(_)=>CustomerPicker(store:widget.store)));if(r!=null)setState((){customerId='${r['id']}';address.text='${r['address']??''}';});}
Future<void> addLine()async{final r=await Navigator.push<Map<String,dynamic>>(context,MaterialPageRoute(builder:(_)=>ItemPicker(store:widget.store)));if(r!=null)setState(()=>lines.add({'itemId':r['id'],'name':r['name'],'quantity':1,'rate':r['rate']??0}));}
double total()=>lines.fold(0,(a,x)=>a+(double.tryParse('${x['rate']}')??0)*(int.tryParse('${x['quantity']}')??0));
@override Widget build(BuildContext c)=>Scaffold(appBar:const Header(back:true),body:ListView(padding:const EdgeInsets.fromLTRB(18,8,18,30),children:[const Text('New Issued Entry',style:TextStyle(color:dark,fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:16),FieldBox(label:'Invoice No.',controller:invoice),FieldBox(label:'Issued date',controller:date),InkWell(onTap:chooseCustomer,child:InputDecorator(decoration:const InputDecoration(labelText:'Customer / Party'),child:Text(customerName(),style:TextStyle(fontSize:16,color:customerId==null?Colors.black45:dark,fontWeight:FontWeight.w600)))),const SizedBox(height:12),FieldBox(label:'Address',controller:address,maxLines:2),const SizedBox(height:20),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('Inventory lines',style:TextStyle(color:dark,fontSize:22,fontWeight:FontWeight.w900)),FilledButton.icon(onPressed:addLine,icon:const Icon(Icons.add),label:const Text('Add Item'))]),const SizedBox(height:10),if(lines.isEmpty)const Empty(text:'Add one or more items. You can keep adding more lines.'),...lines.asMap().entries.map((e)=>Section(child:Row(children:[const Icon(Icons.inventory_2_outlined,color:primary),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${e.value['name']}',style:const TextStyle(color:dark,fontWeight:FontWeight.w900)),Text('Rate ₹${e.value['rate']}  •  Qty ${e.value['quantity']}',style:const TextStyle(color:Colors.black54))])),IconButton(onPressed:()=>setState(()=>lines.removeAt(e.key)),icon:const Icon(Icons.delete_outline,color:Colors.redAccent))]))),const SizedBox(height:12),Section(child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('Total',style:TextStyle(color:dark,fontSize:19,fontWeight:FontWeight.w900)),Text('₹${total().toStringAsFixed(2)}',style:const TextStyle(color:primary,fontSize:22,fontWeight:FontWeight.w900))])),const SizedBox(height:18),SizedBox(height:52,child:FilledButton(onPressed:()async{if(customerId==null||lines.isEmpty)return;await widget.store.add('issued',{'id':uid(),'invoice':invoice.text.trim(),'date':date.text.trim(),'customerId':customerId,'customerName':customerName(),'address':address.text.trim(),'lines':lines,'total':total(),'status':'Issued'});if(c.mounted)Navigator.pop(c);},child:const Text('Save Issued Entry')))]));}

class CustomerPicker extends StatelessWidget{final Store store;const CustomerPicker({required this.store,super.key});@override Widget build(BuildContext c)=>Page(title:'Select Customer',child:Column(children:[if(store.customers.isEmpty)const Empty(text:'No customers. Add a customer first from Customers.'),...store.customers.map((x)=>InkWell(onTap:()=>Navigator.pop(c,x),child:Section(child:Row(children:[const CircleAvatar(backgroundColor:soft,child:Icon(Icons.person_outline,color:primary)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${x['name']}',style:const TextStyle(color:dark,fontWeight:FontWeight.w900)),Text('${x['mobile']}  •  ${x['address']}',maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.black54))])),const Icon(Icons.chevron_right,color:primary)]))))]));}
class ItemPicker extends StatelessWidget{final Store store;const ItemPicker({required this.store,super.key});@override Widget build(BuildContext c)=>Page(title:'Select Item',child:Column(children:[if(store.items.isEmpty)const Empty(text:'No items. Add items first from Items.'),...store.items.map((x)=>InkWell(onTap:()=>Navigator.pop(c,x),child:Section(child:Row(children:[const Icon(Icons.inventory_2_outlined,color:primary,size:30),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${x['name']}',style:const TextStyle(color:dark,fontWeight:FontWeight.w900)),Text('Stock ${x['quantity']}  •  Rate ₹${x['rate']}',style:const TextStyle(color:Colors.black54))])),const Icon(Icons.chevron_right,color:primary)]))))]));}

class ReturnsPage extends StatelessWidget{final Store store;const ReturnsPage({required this.store,super.key});@override Widget build(BuildContext c)=>Page(title:'Returns',actions:[IconButton(onPressed:()=>open(c,ReturnForm(store:store)),icon:const Icon(Icons.add_circle_outline,color:primary))],child:Column(children:[if(store.issued.isEmpty)const Empty(text:'No issued invoices available for return.') else ...store.issued.asMap().entries.map((e)=>DataRowCard(icon:Icons.receipt_long_outlined,title:'${e.value['invoice']}',subtitle:'${e.value['customerName']}  •  ₹${e.value['total']}',onEdit:()=>open(c,ReturnForm(store:store,issued:e.value)))])]);}
class ReturnForm extends StatefulWidget{final Store store;final Map<String,dynamic>? issued;const ReturnForm({required this.store,this.issued,super.key});@override State<ReturnForm>createState()=>_ReturnState();}
class _ReturnState extends State<ReturnForm>{final date=TextEditingController(text:today()),amount=TextEditingController(text:'0'),note=TextEditingController();Map<String,dynamic>? selected;@override void initState(){super.initState();selected=widget.issued;}Future<void>pick()async{final r=await Navigator.push<Map<String,dynamic>>(context,MaterialPageRoute(builder:(_)=>IssuedPicker(store:widget.store)));if(r!=null)setState(()=>selected=r);}@override Widget build(BuildContext c)=>Scaffold(appBar:const Header(back:true),body:ListView(padding:const EdgeInsets.fromLTRB(18,8,18,30),children:[const Text('Return Entry',style:TextStyle(color:dark,fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:16),InkWell(onTap:pick,child:InputDecorator(decoration:const InputDecoration(labelText:'Issued Invoice'),child:Text(selected==null?'Select issued invoice':'${selected!['invoice']}  •  ${selected!['customerName']}'))),const SizedBox(height:12),FieldBox(label:'Return date',controller:date),FieldBox(label:'Return amount (manual)',controller:amount,number:true),FieldBox(label:'Notes',controller:note,maxLines:3),const SizedBox(height:18),SizedBox(height:52,child:FilledButton(onPressed:()async{if(selected==null)return;await widget.store.add('returns',{'id':uid(),'invoice':'${selected!['invoice']}','customerName':'${selected!['customerName']}','date':date.text,'amount':double.tryParse(amount.text)??0,'note':note.text});if(c.mounted)Navigator.pop(c);},child:const Text('Save Return')))]));}
class IssuedPicker extends StatelessWidget{final Store store;const IssuedPicker({required this.store,super.key});@override Widget build(BuildContext c)=>Page(title:'Select Issued Invoice',child:Column(children:[...store.issued.map((x)=>InkWell(onTap:()=>Navigator.pop(c,x),child:Section(child:Row(children:[const Icon(Icons.receipt_long_outlined,color:primary),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${x['invoice']}',style:const TextStyle(color:dark,fontWeight:FontWeight.w900)),Text('${x['customerName']}  •  ₹${x['total']}',style:const TextStyle(color:Colors.black54))])),const Icon(Icons.chevron_right,color:primary)]))))]));}

class ShopManager extends StatelessWidget{final Store store;const ShopManager({required this.store,super.key});@override Widget build(BuildContext c)=>Page(title:'Shop Management',actions:[IconButton(onPressed:()=>open(c,ShopForm(store:store)),icon:const Icon(Icons.add_business_outlined,color:primary))],child:Column(children:[...store.shops.asMap().entries.map((e){final x=e.value;return Padding(padding:const EdgeInsets.only(bottom:10),child:Section(child:Row(children:[const Logo(size:46),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${x['name']}',style:const TextStyle(color:dark,fontSize:17,fontWeight:FontWeight.w900)),Text('${x['owner']}  •  ${x['mobile']}',style:const TextStyle(color:Colors.black54)),Text('${x['address']}',style:const TextStyle(color:Colors.black54))])),PopupMenuButton<String>(onSelected:(v)async{if(v=='edit'){if(c.mounted)await open(c,ShopForm(store:store,index:e.key));}else if(v=='select')await store.selectShop(e.key);else if(v=='delete'&&await confirmDelete(c))await store.deleteShop(e.key);},itemBuilder:(_)=>const[PopupMenuItem(value:'select',child:Text('Use this shop')),PopupMenuItem(value:'edit',child:Text('Edit shop')),PopupMenuItem(value:'delete',child:Text('Delete shop'))])])));}),const SizedBox(height:8),FilledButton.icon(onPressed:()=>open(c,ShopForm(store:store)),icon:const Icon(Icons.add_business),label:const Text('Add New Shop'))]));}
class ShopForm extends StatefulWidget{final Store store;final int? index;const ShopForm({required this.store,this.index,super.key});@override State<ShopForm>createState()=>_ShopFormState();}
class _ShopFormState extends State<ShopForm>{final n=TextEditingController(),o=TextEditingController(),m=TextEditingController(),a=TextEditingController();@override void initState(){super.initState();if(widget.index!=null){final x=widget.store.shops[widget.index!];n.text='${x['name']}';o.text='${x['owner']}';m.text='${x['mobile']}';a.text='${x['address']}';}}@override Widget build(BuildContext c)=>FormPage(title:widget.index==null?'New Shop':'Edit Shop',fields:[FieldBox(label:'Shop name',controller:n),FieldBox(label:'Owner name',controller:o),FieldBox(label:'Mobile',controller:m,number:true),FieldBox(label:'Shop address',controller:a,maxLines:3)],onSave:()async{if(n.text.trim().isEmpty)return;if(widget.index==null)await widget.store.addShop(n.text,o.text,m.text,a.text);else await widget.store.updateShop(n.text,o.text,m.text,a.text);if(c.mounted)Navigator.pop(c);});}

class SettingsPage extends StatelessWidget{final Store store;const SettingsPage({required this.store,super.key});Future<void>check(BuildContext c)async{showDialog(context:c,builder:(_)=>const AlertDialog(content:Row(children:[CircularProgressIndicator(color:primary),SizedBox(width:16),Text('Checking for updates...')])));try{final r=await http.get(Uri.parse('https://api.github.com/repos/shanpalia/RentFlow/releases/latest'),headers:{'Accept':'application/vnd.github+json'});if(c.mounted)Navigator.pop(c);if(!c.mounted)return;final data=r.statusCode==200?jsonDecode(r.body):{};final url='${data['html_url']??'https://github.com/shanpalia/RentFlow/releases'}';showDialog(context:c,builder:(_)=>AlertDialog(title:Text(r.statusCode==200?'Latest release found':'Update check'),content:Text(r.statusCode==200?'Open the latest RentFlow release to download the newest APK.':'No release information was returned.'),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Close')),if(r.statusCode==200)FilledButton(onPressed:()async{final u=Uri.parse(url);if(await canLaunchUrl(u))await launchUrl(u,mode:LaunchMode.externalApplication);},child:const Text('Open Release'))]));}catch(_){if(c.mounted){Navigator.pop(c);ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Could not check for updates.')));}}}@override Widget build(BuildContext c)=>Page(title:'Settings',child:Column(children:[Section(child:Column(children:[const ListTile(leading:Icon(Icons.storefront_outlined,color:primary),title:Text('Current shop'),subtitle:Text('Manage shop, address and owner details')),ListTile(leading:const Icon(Icons.swap_horiz,color:primary),title:const Text('Switch shop'),subtitle:Text('${store.shops.length} shop(s) registered'),onTap:()=>open(c,ShopManager(store:store))),const Divider(height:1),ListTile(leading:const Icon(Icons.system_update_alt,color:primary),title:const Text('Check for updates'),subtitle:const Text('Check the official RentFlow release'),trailing:const Icon(Icons.chevron_right),onTap:()=>check(c))])),const SizedBox(height:14),Section(child:const Column(children:[Text('RentFlow',style:TextStyle(color:dark,fontSize:18,fontWeight:FontWeight.w900)),SizedBox(height:3),Text('By PaliaAPK HUB',style:TextStyle(color:primary,fontWeight:FontWeight.w800)),Text('Developer by ShanPalia',style:TextStyle(color:Colors.black54,fontSize:12))]))]));}

class FormPage extends StatelessWidget{final String title;final List<Widget> fields;final Future<void> Function() onSave;const FormPage({required this.title,required this.fields,required this.onSave,super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:Header(back:true),body:ListView(padding:const EdgeInsets.fromLTRB(18,8,18,30),children:[Text(title,style:const TextStyle(color:dark,fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:18),...fields,const SizedBox(height:12),SizedBox(height:52,child:FilledButton(onPressed:onSave,child:const Text('Save')))]));}
class FieldBox extends StatelessWidget{final String label;final TextEditingController controller;final bool number;final int maxLines;const FieldBox({required this.label,required this.controller,this.number=false,this.maxLines=1,super.key});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.only(bottom:12),child:TextField(controller:controller,maxLines:maxLines,keyboardType:number?const TextInputType.numberWithOptions(decimal:true):TextInputType.text,decoration:InputDecoration(labelText:label,filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(17),borderSide:const BorderSide(color:line)),enabledBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(17),borderSide:const BorderSide(color:line)),focusedBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(17),borderSide:const BorderSide(color:primary,width:1.7)),contentPadding:const EdgeInsets.symmetric(horizontal:17,vertical:16))));}
class Empty extends StatelessWidget{final String text;const Empty({required this.text,super.key});@override Widget build(BuildContext c)=>Section(child:Column(children:[const Icon(Icons.inbox_outlined,color:primary,size:44),const SizedBox(height:8),Text(text,textAlign:TextAlign.center,style:const TextStyle(color:Colors.black54))]));}
class DataRowCard extends StatelessWidget{final IconData icon;final String title,subtitle;final VoidCallback onEdit;final VoidCallback onDelete;const DataRowCard({required this.icon,required this.title,required this.subtitle,required this.onEdit,required this.onDelete,super.key});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.only(bottom:10),child:Section(child:Row(children:[Container(padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:soft,borderRadius:BorderRadius.circular(13)),child:Icon(icon,color:primary)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:dark,fontWeight:FontWeight.w900)),Text(subtitle,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.black54))])),IconButton(onPressed:onEdit,icon:const Icon(Icons.edit_outlined,color:primary)),IconButton(onPressed:onDelete,icon:const Icon(Icons.delete_outline,color:Colors.redAccent))])));}
