import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'app.dart' as old;

const rp = Color(0xFF00A889);
const rd = Color(0xFF10241F);
const rb = Color(0xFFF5FAF8);
const rs = Color(0xFFE7F7F2);
const rl = Color(0xFFDDEBE6);

Future<void> runModern() async { WidgetsFlutterBinding.ensureInitialized(); runApp(const ModernApp()); }

class ModernApp extends StatelessWidget {
  const ModernApp({super.key});
  @override Widget build(BuildContext context) => MaterialApp(
    debugShowCheckedModeBanner: false, title: 'RentFlow',
    theme: ThemeData(useMaterial3: true, scaffoldBackgroundColor: rb, colorScheme: ColorScheme.fromSeed(seedColor: rp), appBarTheme: const AppBarTheme(backgroundColor: rb, foregroundColor: rd, elevation: 0), inputDecorationTheme: InputDecorationTheme(filled: true, fillColor: Colors.white, border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(16)), borderSide: BorderSide.none), enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(16)), borderSide: BorderSide(color: rl)), focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(16)), borderSide: BorderSide(color: rp, width: 1.5)))),
    home: const Splash(),
  );
}

class Logo extends StatelessWidget { final double size; const Logo({this.size = 48, super.key}); @override Widget build(BuildContext c) => Container(width: size, height: size, padding: EdgeInsets.all(size * .07), decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(size * .27), border: Border.all(color: rl)), child: SvgPicture.asset('assets/rentflow_logo.svg')); }

class Splash extends StatefulWidget { const Splash({super.key}); @override State<Splash> createState() => _SplashState(); }
class _SplashState extends State<Splash> { @override void initState() { super.initState(); Future.delayed(const Duration(milliseconds: 900), () { if (mounted) Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => const Shell())); }); } @override Widget build(BuildContext c) => Scaffold(body: Center(child: Column(mainAxisAlignment: MainAxisAlignment.center, children: const [Logo(size: 108), SizedBox(height: 18), Text('RentFlow', style: TextStyle(fontSize: 34, fontWeight: FontWeight.w900, color: rd)), SizedBox(height: 4), Text('By PaliaAPK HUB', style: TextStyle(color: rp, fontWeight: FontWeight.w800)), SizedBox(height: 3), Text('Developer by shanpalia', style: TextStyle(color: Colors.black45))]))); }

class Shell extends StatefulWidget { const Shell({super.key}); @override State<Shell> createState() => _ShellState(); }
class _ShellState extends State<Shell> {
  final old.Store store = old.Store(); int tab = 0; bool loading = true;
  @override void initState() { super.initState(); store.load().then((_) { if (mounted) setState(() => loading = false); }); }
  void refresh() { if (mounted) setState(() {}); }
  Future<void> register() async { await Navigator.push(context, MaterialPageRoute(builder: (_) => old.ShopRegistrationPage(store: store))); refresh(); }
  Future<bool> gate(BuildContext context) async {
    if (store.registered) return true;
    final yes = await showDialog<bool>(context: context, builder: (c) => AlertDialog(title: const Text('Register your shop first'), content: const Text('Register your shop before making an entry. You can keep browsing by choosing Later.'), actions: [TextButton(onPressed: () => Navigator.pop(c, false), child: const Text('Later')), FilledButton.icon(onPressed: () => Navigator.pop(c, true), icon: const Icon(Icons.storefront_rounded), label: const Text('Register Shop'))]));
    if (yes == true && context.mounted) await register();
    return store.registered;
  }
  @override Widget build(BuildContext c) {
    if (loading) return const Scaffold(body: Center(child: CircularProgressIndicator(color: rp)));
    final pages = [Home(store: store, register: register, gate: gate), Inventory(store: store, gate: gate, refresh: refresh), Customers(store: store, gate: gate, refresh: refresh), Rentals(store: store, gate: gate, refresh: refresh), Settings(store: store, register: register)];
    return PopScope(canPop: tab == 0, onPopInvokedWithResult: (didPop, result) { if (!didPop && tab != 0) setState(() => tab = 0); }, child: Scaffold(body: pages[tab], bottomNavigationBar: NavigationBar(height: 76, backgroundColor: Colors.white, indicatorColor: rs, selectedIndex: tab, onDestinationSelected: (v) => setState(() => tab = v), destinations: const [NavigationDestination(icon: Icon(Icons.grid_view_rounded), label: 'Home'), NavigationDestination(icon: Icon(Icons.inventory_2_outlined), label: 'Inventory'), NavigationDestination(icon: Icon(Icons.people_outline_rounded), label: 'Customers'), NavigationDestination(icon: Icon(Icons.assignment_outlined), label: 'Rentals'), NavigationDestination(icon: Icon(Icons.settings_outlined), label: 'Settings')]));
  }
}

class Home extends StatelessWidget {
  final old.Store store; final VoidCallback register; final Future<bool> Function(BuildContext) gate;
  const Home({required this.store, required this.register, required this.gate, super.key});
  @override Widget build(BuildContext c) {
    final issued = store.rentals.fold<int>(0, (n, r) => n + old.asInt(r['qty']) - old.asInt(r['received']));
    final active = store.rentals.where((r) => old.asInt(r['received']) < old.asInt(r['qty'])).length;
    return SafeArea(child: ListView(padding: const EdgeInsets.fromLTRB(18, 18, 18, 24), children: [
      Row(children: [const Logo(size: 48), const SizedBox(width: 10), const Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('RentFlow', style: TextStyle(fontSize: 25, fontWeight: FontWeight.w900, color: rd)), Text('By PaliaAPK HUB', style: TextStyle(fontSize: 12, color: rp, fontWeight: FontWeight.w800))])), InkWell(onTap: register, borderRadius: BorderRadius.circular(18), child: Container(width: 154, padding: const EdgeInsets.all(8), decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(18), border: Border.all(color: rl)), child: Row(children: [Container(width: 36, height: 36, decoration: BoxDecoration(color: rs, borderRadius: BorderRadius.circular(11)), child: const Icon(Icons.storefront_rounded, color: rp)), const SizedBox(width: 7), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('SHOP', style: TextStyle(fontSize: 8, color: rp, fontWeight: FontWeight.w900)), Text(store.registered ? store.shop : 'Register shop', maxLines: 1, overflow: TextOverflow.ellipsis, style: const TextStyle(fontSize: 10, fontWeight: FontWeight.w900, color: rd)), Text(store.registered ? store.owner : 'Tap to setup', maxLines: 1, overflow: TextOverflow.ellipsis, style: const TextStyle(fontSize: 9, color: Colors.black54))]))])))]),
      const SizedBox(height: 20),
      if (!store.registered) ...[Container(padding: const EdgeInsets.all(16), decoration: BoxDecoration(color: rd, borderRadius: BorderRadius.circular(22)), child: Row(children: [const Icon(Icons.storefront_rounded, color: Colors.white), const SizedBox(width: 10), const Expanded(child: Text('Register your shop to unlock entries.', style: TextStyle(color: Colors.white, fontWeight: FontWeight.w800))), TextButton(onPressed: register, child: const Text('Register', style: TextStyle(color: Colors.white)))])), const SizedBox(height: 18)],
      Row(children: [Stat('Items', '${store.items.length}', Icons.inventory_2_outlined), const SizedBox(width: 10), Stat('Customers', '${store.customers.length}', Icons.people_outline_rounded)]), const SizedBox(height: 10), Row(children: [Stat('Active', '$active', Icons.assignment_outlined), const SizedBox(width: 10), Stat('Issued Qty', '$issued', Icons.local_shipping_outlined)]),
      const SizedBox(height: 24), const Text('Quick actions', style: TextStyle(fontSize: 21, fontWeight: FontWeight.w900, color: rd)), const SizedBox(height: 11), Row(children: [ActionTile('Add Item', Icons.add_box_outlined, () async { if (await gate(c) && c.mounted) await itemEditor(c, store); }), const SizedBox(width: 10), ActionTile('Customer', Icons.person_add_alt_1_outlined, () async { if (await gate(c) && c.mounted) await customerEditor(c, store); }), const SizedBox(width: 10), ActionTile('New Rental', Icons.receipt_long_outlined, () async { if (await gate(c) && c.mounted) await rentalEditor(c, store); })]),
      const SizedBox(height: 24), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [const Text('Recent rentals', style: TextStyle(fontSize: 21, fontWeight: FontWeight.w900, color: rd)), Text(old.money(store.rentals.fold<double>(0, (n, r) => n + old.asDouble(r['amount']))), style: const TextStyle(color: rp, fontWeight: FontWeight.w900))]), const SizedBox(height: 10), if (store.rentals.isEmpty) const Empty() else ...store.rentals.reversed.take(5).map((r) => RentalCard(r)),
    ]));
  }
}

class Stat extends StatelessWidget { final String label, value; final IconData icon; const Stat(this.label, this.value, this.icon, {super.key}); @override Widget build(BuildContext c) => Expanded(child: Container(padding: const EdgeInsets.all(15), decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(22), border: Border.all(color: rl)), child: Row(children: [Container(width: 43, height: 43, decoration: BoxDecoration(color: rs, borderRadius: BorderRadius.circular(14)), child: Icon(icon, color: rp)), const SizedBox(width: 10), Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(value, style: const TextStyle(fontSize: 22, fontWeight: FontWeight.w900, color: rd)), Text(label, style: const TextStyle(color: Colors.black54, fontSize: 12))])])); }
class ActionTile extends StatelessWidget { final String text; final IconData icon; final VoidCallback onTap; const ActionTile(this.text, this.icon, this.onTap, {super.key}); @override Widget build(BuildContext c) => Expanded(child: InkWell(onTap: onTap, borderRadius: BorderRadius.circular(20), child: Container(height: 104, decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(20), border: Border.all(color: rl)), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [Container(width: 44, height: 44, decoration: BoxDecoration(color: rs, borderRadius: BorderRadius.circular(14)), child: Icon(icon, color: rp)), const SizedBox(height: 8), Text(text, style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w900, color: rd))])))); }
class Empty extends StatelessWidget { const Empty({super.key}); @override Widget build(BuildContext c) => Container(padding: const EdgeInsets.all(28), decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(23), border: Border.all(color: rl)), child: const Column(children: [Icon(Icons.receipt_long_outlined, color: rp, size: 45), SizedBox(height: 12), Text('No rentals yet', style: TextStyle(fontWeight: FontWeight.w900, color: rd, fontSize: 16)), SizedBox(height: 5), Text('Saved rental invoices will appear here.', textAlign: TextAlign.center, style: TextStyle(color: Colors.black54))])); }

class Inventory extends StatelessWidget {
  final old.Store store; final Future<bool> Function(BuildContext) gate; final VoidCallback refresh;
  const Inventory({required this.store, required this.gate, required this.refresh, super.key});
  @override Widget build(BuildContext c) => Scaffold(appBar: AppBar(title: const Text('Inventory', style: TextStyle(fontWeight: FontWeight.w900)), actions: [IconButton(onPressed: () async { if (await gate(c) && c.mounted) { await itemEditor(c, store); refresh(); } }, icon: const Icon(Icons.add_rounded))]), body: store.items.isEmpty ? const Padding(padding: EdgeInsets.all(18), child: Empty()) : ListView.builder(padding: const EdgeInsets.all(18), itemCount: store.items.length, itemBuilder: (_, i) { final x = store.items[i]; final qty = old.asInt(x['qty']); final issued = old.asInt(x['issued_qty']); final available = (qty - issued).clamp(0, qty); return Container(margin: const EdgeInsets.only(bottom: 10), padding: const EdgeInsets.all(14), decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(20), border: Border.all(color: rl)), child: Row(children: [Container(width: 48, height: 48, decoration: BoxDecoration(color: rs, borderRadius: BorderRadius.circular(14)), child: Center(child: Text('${x['serial'] ?? i + 1}', style: const TextStyle(color: rp, fontWeight: FontWeight.w900)))), const SizedBox(width: 12), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('${x['name']}', style: const TextStyle(fontWeight: FontWeight.w900, color: rd)), Text('Total $qty  •  Issued $issued  •  Available $available', style: const TextStyle(color: Colors.black54, fontSize: 12)), Text('${old.money(x['rent'])} / day', style: const TextStyle(color: rp, fontWeight: FontWeight.w800))])), IconButton.filledTonal(onPressed: () async { await addInventory(c, store, x); refresh(); }, icon: const Icon(Icons.add_rounded, color: rp), tooltip: 'Add more inventory'), IconButton(onPressed: () async { await itemEditor(c, store, existing: x); refresh(); }, icon: const Icon(Icons.edit_outlined))])); }));
}

Future<void> itemEditor(BuildContext context, old.Store store, {Map<String, dynamic>? existing}) async {
  final name = TextEditingController(text: '${existing?['name'] ?? ''}'); final qty = TextEditingController(text: '${existing?['qty'] ?? 1}'); final rent = TextEditingController(text: '${existing?['rent'] ?? 0}'); final days = TextEditingController(text: '${existing?['rent_days'] ?? 1}');
  await showDialog<void>(context: context, builder: (c) => AlertDialog(title: Text(existing == null ? 'Add Inventory Item' : 'Edit Inventory Item'), content: SingleChildScrollView(child: Column(mainAxisSize: MainAxisSize.min, children: [TextField(controller: name, decoration: const InputDecoration(labelText: 'Item name')), const SizedBox(height: 10), TextField(controller: qty, keyboardType: TextInputType.number, decoration: const InputDecoration(labelText: 'Total quantity')), const SizedBox(height: 10), TextField(controller: rent, keyboardType: TextInputType.number, decoration: const InputDecoration(labelText: 'Rent price per day')), const SizedBox(height: 10), TextField(controller: days, keyboardType: TextInputType.number, decoration: const InputDecoration(labelText: 'Rent days'))])), actions: [TextButton(onPressed: () => Navigator.pop(c), child: const Text('Cancel')), FilledButton(onPressed: () async { if (name.text.trim().isEmpty) return; final q = int.tryParse(qty.text) ?? 0; final r = double.tryParse(rent.text) ?? 0; final d = int.tryParse(days.text) ?? 1; if (existing == null) { store.items.add({'serial': store.items.length + 1, 'name': name.text.trim(), 'qty': q, 'issued_qty': 0, 'rent': r, 'rent_days': d}); } else { existing['name'] = name.text.trim(); existing['qty'] = q; existing['rent'] = r; existing['rent_days'] = d; existing['issued_qty'] = old.asInt(existing['issued_qty']); } await store.save(); if (c.mounted) Navigator.pop(c); }, child: const Text('Save'))]));
  name.dispose(); qty.dispose(); rent.dispose(); days.dispose();
}
Future<void> addInventory(BuildContext context, old.Store store, Map<String, dynamic> item) async { final q = TextEditingController(text: '1'); await showDialog<void>(context: context, builder: (c) => AlertDialog(title: Text('Add more: ${item['name']}'), content: TextField(controller: q, keyboardType: TextInputType.number, decoration: const InputDecoration(labelText: 'Quantity to add')), actions: [TextButton(onPressed: () => Navigator.pop(c), child: const Text('Cancel')), FilledButton(onPressed: () async { final n = int.tryParse(q.text) ?? 0; if (n > 0) { item['qty'] = old.asInt(item['qty']) + n; await store.save(); } if (c.mounted) Navigator.pop(c); }, child: const Text('Add Inventory'))])); q.dispose(); }

class Customers extends StatelessWidget {
  final old.Store store; final Future<bool> Function(BuildContext) gate; final VoidCallback refresh; const Customers({required this.store, required this.gate, required this.refresh, super.key});
  @override Widget build(BuildContext c) => Scaffold(appBar: AppBar(title: const Text('Customers', style: TextStyle(fontWeight: FontWeight.w900)), actions: [IconButton(onPressed: () async { if (await gate(c) && c.mounted) { await customerEditor(c, store); refresh(); } }, icon: const Icon(Icons.person_add_alt_1_rounded))]), body: store.customers.isEmpty ? const Padding(padding: EdgeInsets.all(18), child: Empty()) : ListView.builder(padding: const EdgeInsets.all(18), itemCount: store.customers.length, itemBuilder: (_, i) { final x = store.customers[i]; return Card(child: ListTile(leading: CircleAvatar(backgroundColor: rs, child: Text('${x['name']}'.isEmpty ? '?' : '${x['name']}'[0].toUpperCase(), style: const TextStyle(color: rp))), title: Text('${x['name']}', style: const TextStyle(fontWeight: FontWeight.w900)), subtitle: Text('${x['phone'] ?? ''}\n${x['address'] ?? ''}'), isThreeLine: true)); }));
}
Future<void> customerEditor(BuildContext context, old.Store store) async { final name = TextEditingController(); final phone = TextEditingController(); final address = TextEditingController(); await showDialog<void>(context: context, builder: (c) => AlertDialog(title: const Text('Add Customer'), content: SingleChildScrollView(child: Column(mainAxisSize: MainAxisSize.min, children: [TextField(controller: name, decoration: const InputDecoration(labelText: 'Party name')), const SizedBox(height: 10), TextField(controller: phone, keyboardType: TextInputType.phone, decoration: const InputDecoration(labelText: 'Mobile number')), const SizedBox(height: 10), TextField(controller: address, maxLines: 2, decoration: const InputDecoration(labelText: 'Address'))])), actions: [TextButton(onPressed: () => Navigator.pop(c), child: const Text('Cancel')), FilledButton(onPressed: () async { if (name.text.trim().isEmpty) return; store.customers.add({'name': name.text.trim(), 'phone': phone.text.trim(), 'address': address.text.trim()}); await store.save(); if (c.mounted) Navigator.pop(c); }, child: const Text('Save'))])); name.dispose(); phone.dispose(); address.dispose(); }

class Rentals extends StatelessWidget { final old.Store store; final Future<bool> Function(BuildContext) gate; final VoidCallback refresh; const Rentals({required this.store, required this.gate, required this.refresh, super.key}); @override Widget build(BuildContext c) => Scaffold(appBar: AppBar(title: const Text('Rental Invoices', style: TextStyle(fontWeight: FontWeight.w900)), actions: [IconButton(onPressed: () async { if (await gate(c) && c.mounted) { await rentalEditor(c, store); refresh(); } }, icon: const Icon(Icons.add_rounded))]), body: store.rentals.isEmpty ? const Padding(padding: EdgeInsets.all(18), child: Empty()) : ListView.builder(padding: const EdgeInsets.all(18), itemCount: store.rentals.length, itemBuilder: (_, i) => RentalCard(store.rentals[store.rentals.length - 1 - i]))); }
class RentalCard extends StatelessWidget { final Map<String, dynamic> r; const RentalCard(this.r, {super.key}); @override Widget build(BuildContext c) => Container(margin: const EdgeInsets.only(bottom: 10), padding: const EdgeInsets.all(15), decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(18), border: Border.all(color: rl)), child: Row(children: [Container(width: 45, height: 45, decoration: BoxDecoration(color: rs, borderRadius: BorderRadius.circular(13)), child: const Icon(Icons.receipt_long_rounded, color: rp)), const SizedBox(width: 12), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('${r['invoice_no'] ?? 'Invoice'}', style: const TextStyle(color: rp, fontWeight: FontWeight.w900)), Text('${r['customer']}', style: const TextStyle(fontWeight: FontWeight.w900, color: rd)), Text('${r['item']} • Qty ${r['qty']} • ${r['date']}', style: const TextStyle(color: Colors.black54, fontSize: 12))])), Text(old.money(r['amount']), style: const TextStyle(fontWeight: FontWeight.w900, color: rd))])); }

Future<void> rentalEditor(BuildContext context, old.Store store) async {
  if (store.items.isEmpty) { await showDialog<void>(context: context, builder: (c) => AlertDialog(title: const Text('Inventory required'), content: const Text('Add at least one inventory item before creating a rental invoice.'), actions: [FilledButton(onPressed: () => Navigator.pop(c), child: const Text('OK'))])); return; }
  final party = TextEditingController(); final address = TextEditingController(); final phone = TextEditingController(); int selected = 0; int qty = 1; final date = DateTime.now();
  await showDialog<void>(context: context, builder: (c) => StatefulBuilder(builder: (c, set) {
    final item = store.items[selected]; final available = (old.asInt(item['qty']) - old.asInt(item['issued_qty'])).clamp(0, old.asInt(item['qty'])); if (available > 0 && qty > available) qty = available;
    return AlertDialog(title: const Text('New Rental Invoice'), content: SingleChildScrollView(child: Column(mainAxisSize: MainAxisSize.min, children: [
      _readOnlyLine('Issued date', '${date.day.toString().padLeft(2, '0')}/${date.month.toString().padLeft(2, '0')}/${date.year}', Icons.event_outlined), const SizedBox(height: 10),
      TextField(controller: party, decoration: const InputDecoration(labelText: 'Party name *', prefixIcon: Icon(Icons.person_outline))), const SizedBox(height: 10), TextField(controller: phone, keyboardType: TextInputType.phone, decoration: const InputDecoration(labelText: 'Mobile number', prefixIcon: Icon(Icons.phone_outlined))), const SizedBox(height: 10), TextField(controller: address, maxLines: 2, decoration: const InputDecoration(labelText: 'Party address', prefixIcon: Icon(Icons.location_on_outlined))), const SizedBox(height: 10),
      DropdownButtonFormField<int>(value: selected, decoration: const InputDecoration(labelText: 'Inventory item', prefixIcon: Icon(Icons.inventory_2_outlined)), items: List.generate(store.items.length, (i) => DropdownMenuItem(value: i, child: Text('${store.items[i]['serial'] ?? i + 1}. ${store.items[i]['name']}'))), onChanged: (v) { if (v != null) set(() { selected = v; qty = 1; }); }), const SizedBox(height: 10),
      Row(children: [const Text('Issued quantity', style: TextStyle(fontWeight: FontWeight.w800)), const Spacer(), IconButton(onPressed: qty > 1 ? () => set(() => qty--) : null, icon: const Icon(Icons.remove_circle_outline)), Text('$qty', style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w900)), IconButton(onPressed: qty < available ? () => set(() => qty++) : null, icon: const Icon(Icons.add_circle_outline, color: rp))]), Align(alignment: Alignment.centerLeft, child: Text('Available: $available', style: const TextStyle(color: Colors.black54, fontSize: 12))), const SizedBox(height: 10), Container(padding: const EdgeInsets.all(14), decoration: BoxDecoration(color: rs, borderRadius: BorderRadius.circular(16)), child: Row(children: [const Text('Total rent', style: TextStyle(fontWeight: FontWeight.w800)), const Spacer(), Text(old.money(old.asDouble(item['rent']) * qty), style: const TextStyle(fontSize: 20, fontWeight: FontWeight.w900, color: rp))])),
    ])), actions: [TextButton(onPressed: () => Navigator.pop(c), child: const Text('Cancel')), FilledButton.icon(onPressed: available < 1 || party.text.trim().isEmpty ? null : () async { final invoice = 'INV-${DateTime.now().millisecondsSinceEpoch.toString().substring(6)}'; final amount = old.asDouble(item['rent']) * qty; item['issued_qty'] = old.asInt(item['issued_qty']) + qty; final rental = {'invoice_no': invoice, 'date': '${date.day.toString().padLeft(2, '0')}/${date.month.toString().padLeft(2, '0')}/${date.year}', 'customer': party.text.trim(), 'phone': phone.text.trim(), 'address': address.text.trim(), 'item': '${item['name']}', 'item_serial': item['serial'] ?? selected + 1, 'qty': qty, 'received': 0, 'amount': amount, 'rent_days': item['rent_days'] ?? 1}; store.rentals.add(rental); await store.save(); if (c.mounted) { Navigator.pop(c); await showInvoicePreview(c, store, rental); } }, icon: const Icon(Icons.visibility_outlined), label: const Text('Save & Preview'))]);
  }));
  party.dispose(); address.dispose(); phone.dispose();
}
Widget _readOnlyLine(String title, String value, IconData icon) => InputDecorator(decoration: InputDecoration(labelText: title, prefixIcon: Icon(icon)), child: Text(value, style: const TextStyle(fontWeight: FontWeight.w700)));

Future<void> showInvoicePreview(BuildContext context, old.Store store, Map<String, dynamic> r) async { await showDialog<void>(context: context, builder: (c) => AlertDialog(title: Row(children: [const Expanded(child: Text('Invoice Preview', style: TextStyle(fontWeight: FontWeight.w900))), Text('${r['invoice_no']}', style: const TextStyle(color: rp, fontSize: 12))]), content: SingleChildScrollView(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(store.shop.isEmpty ? 'RentFlow' : store.shop, style: const TextStyle(fontWeight: FontWeight.w900, fontSize: 18)), const Text('By PaliaAPK HUB'), const Divider(), Text('Issued: ${r['date']}'), Text('Party: ${r['customer']}'), if ('${r['phone']}'.isNotEmpty) Text('Mobile: ${r['phone']}'), if ('${r['address']}'.isNotEmpty) Text('Address: ${r['address']}'), const SizedBox(height: 12), Text('Inventory: ${r['item']}'), Text('Srl: ${r['item_serial']}'), Text('Issued Qty: ${r['qty']}'), Text('Rent: ${old.money(r['amount'])}'), const SizedBox(height: 10), Text('Total: ${old.money(r['amount'])}', style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w900, color: rp))])), actions: [TextButton(onPressed: () => Navigator.pop(c), child: const Text('Close')), FilledButton.icon(onPressed: () async { await printInvoice(store, r); }, icon: const Icon(Icons.picture_as_pdf_outlined), label: const Text('Save PDF'))])); }

Future<void> printInvoice(old.Store store, Map<String, dynamic> r) async {
  final doc = pw.Document();
  doc.addPage(pw.Page(pageFormat: pw.PdfPageFormat.a4, build: (_) => pw.Padding(padding: const pw.EdgeInsets.all(28), child: pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
    pw.Text(store.shop.isEmpty ? 'RentFlow' : store.shop, style: pw.TextStyle(fontSize: 25, fontWeight: pw.FontWeight.bold)), pw.Text('RentFlow • By PaliaAPK HUB'), pw.SizedBox(height: 18), pw.Text('INVOICE ${r['invoice_no']}', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)), pw.SizedBox(height: 8), pw.Text('Issued Date: ${r['date']}'), pw.SizedBox(height: 12), pw.Text('Party: ${r['customer']}'), pw.Text('Mobile: ${r['phone']}'), pw.Text('Address: ${r['address']}'), pw.SizedBox(height: 18),
    pw.Table(border: pw.TableBorder.all(), children: [pw.TableRow(children: [pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text('Srl / Inventory')), pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text('Issued Qty')), pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text('Rent'))]), pw.TableRow(children: [pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text('${r['item_serial']} / ${r['item']}')), pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text('${r['qty']}')), pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text(old.money(r['amount'])))] )]), pw.SizedBox(height: 20), pw.Align(alignment: pw.Alignment.centerRight, child: pw.Text('TOTAL ${old.money(r['amount'])}', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold))), pw.Spacer(), pw.Text('Developer by shanpalia'),
  ])));
  await Printing.layoutPdf(onLayout: (_) async => doc.save());
}

class Settings extends StatelessWidget { final old.Store store; final VoidCallback register; const Settings({required this.store, required this.register, super.key}); @override Widget build(BuildContext c) => Scaffold(appBar: AppBar(title: const Text('Settings', style: TextStyle(fontWeight: FontWeight.w900))), body: ListView(padding: const EdgeInsets.all(18), children: [Container(padding: const EdgeInsets.all(18), decoration: BoxDecoration(color: rd, borderRadius: BorderRadius.circular(25)), child: Row(children: [const Logo(size: 62), const SizedBox(width: 14), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(store.registered ? store.shop : 'Shop not registered', style: const TextStyle(color: Colors.white, fontSize: 20, fontWeight: FontWeight.w900)), Text(store.registered ? store.owner : 'Register your shop', style: const TextStyle(color: Colors.white70)), if (store.phone.isNotEmpty) Text(store.phone, style: const TextStyle(color: Colors.white70)), if (store.address.isNotEmpty) Text(store.address, maxLines: 2, overflow: TextOverflow.ellipsis, style: const TextStyle(color: Colors.white70))])), IconButton(onPressed: register, icon: const Icon(Icons.edit_outlined, color: Colors.white))])), const SizedBox(height: 18), Card(child: ListTile(leading: const Icon(Icons.system_update_alt_rounded, color: rp), title: const Text('Check for App Update', style: TextStyle(fontWeight: FontWeight.w900)), subtitle: const Text('Check the latest RentFlow version'), onTap: () => old.checkUpdate(c))), const SizedBox(height: 14), Card(child: ListTile(leading: const Logo(size: 46), title: const Text('RentFlow', style: TextStyle(fontWeight: FontWeight.w900, fontSize: 18)), subtitle: const Text('By PaliaAPK HUB\nDeveloper by shanpalia')))])); }
