import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:image_picker/image_picker.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:shared_preferences/shared_preferences.dart';

const emerald = Color(0xFF008F78);
const emeraldDark = Color(0xFF006B5A);
const emeraldSoft = Color(0xFFE7F6F1);
const pageBg = Color(0xFFF5F8F7);
const ink = Color(0xFF172521);
const line = Color(0xFFD8E5E1);

void startRentFlowFixed() { WidgetsFlutterBinding.ensureInitialized(); runApp(const RentFlowApp()); }
class RentFlowApp extends StatelessWidget { const RentFlowApp({super.key}); @override Widget build(BuildContext c) => MaterialApp(debugShowCheckedModeBanner:false,title:'RentFlow',theme:ThemeData(useMaterial3:true,scaffoldBackgroundColor:pageBg,colorScheme:ColorScheme.fromSeed(seedColor:emerald),appBarTheme:const AppBarTheme(backgroundColor:Colors.white,foregroundColor:ink,elevation:0),inputDecorationTheme:const InputDecorationTheme(filled:true,fillColor:Colors.white)),home:const HomePage()); }

class RentDB extends ChangeNotifier {
  SharedPreferences? prefs; List<Map<String,dynamic>> shops=[]; int active=0;
  bool get ready=>prefs!=null; Map<String,dynamic> get shop=>shops.isEmpty?<String,dynamic>{}:shops[active];
  Future<void> load() async { prefs=await SharedPreferences.getInstance(); try{final r=jsonDecode(prefs!.getString('rentflow_data')??'[]');if(r is List)shops=r.whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList();}catch(_){shops=[];} active=prefs!.getInt('rentflow_active')??0;if(active<0||active>=shops.length)active=0;notifyListeners(); }
  Future<void> save() async {await prefs?.setString('rentflow_data',jsonEncode(shops));await prefs?.setInt('rentflow_active',active);notifyListeners();}
  List<Map<String,dynamic>> records(String k){final v=shop[k];if(v is! List)return[];return v.whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList();}
  Future<void> addShop(Map<String,dynamic>d)async{shops.add({...d,'items':[],'customers':[],'issues':[],'returns':[]});active=shops.length-1;await save();}
  Future<void> updateShop(Map<String,dynamic>d)async{shop.addAll(d);await save();}
  Future<void> addRecord(String k,Map<String,dynamic>d)async{if(shop[k] is! List)shop[k]=[];(shop[k] as List).add(d);await save();}
  Future<void> editRecord(String k,int i,Map<String,dynamic>d)async{(shop[k] as List)[i]=d;await save();}
  Future<void> stock(String id,int delta)async{final a=shop['items'] as List? ?? [];for(var i=0;i<a.length;i++){final x=Map<String,dynamic>.from(a[i] as Map);if('${x['id']}'==id){x['quantity']=(int.tryParse('${x['quantity']??0}')??0)+delta;if((x['quantity'] as int)<0)x['quantity']=0;a[i]=x;break;}}await save();}
}
final db=RentDB();
String uid()=>DateTime.now().microsecondsSinceEpoch.toString(); String today()=>DateTime.now().toIso8601String().substring(0,10); String money(dynamic v)=>'₹${(double.tryParse('$v')??0).toStringAsFixed(2)}';
List<Map<String,dynamic>> maps(dynamic v)=>v is List?v.whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList():[];
int daysBetween(String a,String b){final x=DateTime.tryParse(a)??DateTime.now();final y=DateTime.tryParse(b)??DateTime.now();final d=y.difference(x).inDays;return d<1?1:d;}
void openPage(BuildContext c,Widget p)=>Navigator.push(c,MaterialPageRoute(builder:(_)=>p));

class Header extends StatelessWidget implements PreferredSizeWidget{final bool back;const Header({super.key,this.back=false});@override Size get preferredSize=>const Size.fromHeight(62);@override Widget build(BuildContext c)=>AppBar(leading:back?IconButton(onPressed:()=>Navigator.pop(c),icon:const Icon(Icons.arrow_back_rounded)):Builder(builder:(x)=>IconButton(onPressed:()=>Scaffold.of(x).openDrawer(),icon:const Icon(Icons.menu_rounded,size:30))),title:Row(children:[SvgPicture.asset('assets/rentflow_logo.svg',width:34,height:34),const SizedBox(width:10),const Text('RentFlow by PaliaAPK HUB',style:TextStyle(fontSize:17,fontWeight:FontWeight.w900))]),bottom:const PreferredSize(preferredSize:Size.fromHeight(1),child:Divider(height:1,color:line)));}
class _M{final String title;final IconData icon;final Widget page;const _M(this.title,this.icon,this.page);}
class DrawerMenu extends StatelessWidget{const DrawerMenu({super.key});void go(BuildContext c,Widget p){Navigator.pop(c);openPage(c,p);}@override Widget build(BuildContext c)=>Drawer(child:SafeArea(child:Column(children:[Padding(padding:const EdgeInsets.all(20),child:Row(children:[SvgPicture.asset('assets/rentflow_logo.svg',width:48,height:48),const SizedBox(width:12),const Text('RentFlow\nPaliaAPK HUB',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900))])),const Divider(),Expanded(child:ListView(children:[_M('Dashboard',Icons.dashboard_rounded,HomePage()),_M('Inventory',Icons.inventory_2_rounded,ItemsPage()),_M('Customers / Parties',Icons.people_alt_rounded,CustomersPage()),_M('Issued / New Invoice',Icons.outbox_rounded,IssuePage()),_M('Returns',Icons.assignment_return_rounded,ReturnPage()),_M('Inventory Register',Icons.table_rows_rounded,InventoryPage()),_M('Reports / Bills',Icons.receipt_long_rounded,BillsPage()),_M('Shop / Company',Icons.store_rounded,ShopPage()),_M('Settings / About',Icons.settings_rounded,SettingsPage())].map((m)=>ListTile(leading:Icon(m.icon,color:emerald),title:Text(m.title,style:const TextStyle(fontWeight:FontWeight.w700)),onTap:()=>go(c,m.page)).toList())),),const Padding(padding:EdgeInsets.all(16),child:Text('By PaliaAPK HUB • Developer by shanpalia',style:TextStyle(color:Colors.black45,fontWeight:FontWeight.w700))]))));}

class HomePage extends StatefulWidget{const HomePage({super.key});@override State<HomePage>createState()=>_HomeState();}
class _HomeState extends State<HomePage>{int tab=0;@override void initState(){super.initState();db.load();}@override Widget build(BuildContext c)=>AnimatedBuilder(animation:db,builder:(_,__) {if(!db.ready)return const Scaffold(body:Center(child:CircularProgressIndicator(color:emerald)));return Scaffold(appBar:const Header(),drawer:const DrawerMenu(),body:ListView(padding:const EdgeInsets.all(16),children:[shopCard(c),const SizedBox(height:18),const Text('Quick Actions',style:TextStyle(fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:10),GridView.count(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisCount:2,mainAxisSpacing:10,crossAxisSpacing:10,childAspectRatio:1.45,children:[action('New Invoice',Icons.receipt_long_rounded,()=>openPage(c,const IssuePage())),action('Return',Icons.assignment_return_rounded,()=>openPage(c,const ReturnPage())),action('Add Item',Icons.add_box_rounded,()=>openPage(c,const ItemForm())),action('Add Customer',Icons.person_add_rounded,()=>openPage(c,const CustomerForm())),action('Inventory',Icons.inventory_2_rounded,()=>openPage(c,const ItemsPage())),action('Reports / Bills',Icons.picture_as_pdf_rounded,()=>openPage(c,const BillsPage()))]),const SizedBox(height:18),Row(children:[stat('Items',db.records('items').length,Icons.inventory_2),stat('Parties',db.records('customers').length,Icons.people),stat('Issued',db.records('issues').length,Icons.outbox)]),const SizedBox(height:24),const Center(child:Text('RentFlow • By PaliaAPK HUB • Developer by shanpalia',style:TextStyle(color:Colors.black45,fontWeight:FontWeight.w700)))]),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(v){setState(()=>tab=v);if(v==1)openPage(c,const ItemsPage());if(v==2)openPage(c,const IssuePage());if(v==3)openPage(c,const ReturnPage());if(v==4)openPage(c,const SettingsPage());},destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Home'),NavigationDestination(icon:Icon(Icons.inventory_2_outlined),label:'Inventory'),NavigationDestination(icon:Icon(Icons.outbox_outlined),label:'Issued'),NavigationDestination(icon:Icon(Icons.assignment_return_outlined),label:'Returns'),NavigationDestination(icon:Icon(Icons.settings_outlined),label:'About')]);});
Widget shopCard(BuildContext c)=>Card(elevation:0,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(20),side:const BorderSide(color:line)),child:Padding(padding:const EdgeInsets.all(16),child:Row(children:[Container(width:66,height:66,clipBehavior:Clip.antiAlias,decoration:BoxDecoration(color:emeraldSoft,borderRadius:BorderRadius.circular(16)),child:db.shop['image']!=null&&'${db.shop['image']}'.isNotEmpty?Image.file(File('${db.shop['image']}'),fit:BoxFit.cover,errorBuilder:(_,__,___)=>const Icon(Icons.store_rounded,color:emerald,size:34)):const Icon(Icons.store_rounded,color:emerald,size:34)),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${db.shop['name']??'Register your shop'}',style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900)),Text('${db.shop['owner']??''}  ${db.shop['mobile']??''}',style:const TextStyle(color:Colors.black54)),Text('${db.shop['address']??'Add your shop information'}',maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.black54))])),IconButton(onPressed:()=>openPage(c,const ShopPage()),icon:const Icon(Icons.edit_outlined,color:emerald))])));
Widget action(String t,IconData i,VoidCallback f)=>ActionCard(t,i,f);Widget stat(String t,int n,IconData i)=>Expanded(child:Card(elevation:0,child:Padding(padding:const EdgeInsets.all(12),child:Column(children:[Icon(i,color:emerald),Text('$n',style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900)),Text(t,style:const TextStyle(color:Colors.black54))]))));}
class ActionCard extends StatelessWidget{final String title;final IconData icon;final VoidCallback onTap;const ActionCard(this.title,this.icon,this.onTap,{super.key});@override Widget build(BuildContext c)=>Card(elevation:0,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(18),side:const BorderSide(color:line)),child:InkWell(onTap:onTap,borderRadius:BorderRadius.circular(18),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(icon,color:emerald,size:30),const SizedBox(height:8),Text(title,style:const TextStyle(fontWeight:FontWeight.w800))])));}

class Frame extends StatelessWidget{final String title;final Widget child;const Frame(this.title,this.child,{super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:const Header(back:true),body:ListView(padding:const EdgeInsets.all(16),children:[Text(title,style:const TextStyle(fontSize:28,fontWeight:FontWeight.w900,color:ink)),Container(height:4,margin:const EdgeInsets.symmetric(vertical:12),decoration:BoxDecoration(color:emerald,borderRadius:BorderRadius.circular(5))),child]));}
class Field extends StatelessWidget{final String label;final TextEditingController c;final int maxLines;final TextInputType? type;const Field(this.label,this.c,{super.key,this.maxLines=1,this.type});@override Widget build(BuildContext x)=>Padding(padding:const EdgeInsets.only(bottom:12),child:TextField(controller:c,maxLines:maxLines,keyboardType:type,decoration:InputDecoration(labelText:label,border:OutlineInputBorder(borderRadius:BorderRadius.circular(14)))));}
class SaveBtn extends StatelessWidget{final String text;final VoidCallback onTap;const SaveBtn(this.text,this.onTap,{super.key});@override Widget build(BuildContext c)=>SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:onTap,icon:const Icon(Icons.save_rounded),label:Padding(padding:const EdgeInsets.all(12),child:Text(text,style:const TextStyle(fontWeight:FontWeight.w800))));}

class ShopPage extends StatefulWidget{const ShopPage({super.key});@override State<ShopPage>createState()=>_ShopState();}
class _ShopState extends State<ShopPage>{late TextEditingController n,o,m,a;String image='';@override void initState(){super.initState();final x=db.shop;n=TextEditingController(text:'${x['name']??''}');o=TextEditingController(text:'${x['owner']??''}');m=TextEditingController(text:'${x['mobile']??''}');a=TextEditingController(text:'${x['address']??''}');image='${x['image']??''}';}@override void dispose(){n.dispose();o.dispose();m.dispose();a.dispose();super.dispose();}Future<void>pick()async{final x=await ImagePicker().pickImage(source:ImageSource.gallery);if(x!=null)setState(()=>image=x.path);}Future<void>save()async{if(n.text.trim().isEmpty)return;final d={'name':n.text.trim(),'owner':o.text.trim(),'mobile':m.text.trim(),'address':a.text.trim(),'image':image};if(db.shops.isEmpty)await db.addShop(d);else await db.updateShop(d);if(mounted)Navigator.pop(context);}@override Widget build(BuildContext c)=>Frame('Shop / Company',Column(children:[GestureDetector(onTap:pick,child:Container(width:100,height:100,clipBehavior:Clip.antiAlias,decoration:BoxDecoration(color:emeraldSoft,borderRadius:BorderRadius.circular(22)),child:image.isNotEmpty?Image.file(File(image),fit:BoxFit.cover,errorBuilder:(_,__,___)=>const Icon(Icons.add_a_photo,color:emerald,size:34)):const Icon(Icons.add_a_photo,color:emerald,size:34))),const SizedBox(height:8),const Text('Tap to add shop image',style:TextStyle(color:Colors.black54)),const SizedBox(height:18),Field('Shop Name',n),Field('Owner Name',o),Field('Mobile Number',m,type:TextInputType.phone),Field('Address',a,maxLines:3),SaveBtn('Save Shop',save)]));}

class ItemsPage extends StatelessWidget{const ItemsPage({super.key});@override Widget build(BuildContext c){final a=db.records('items');return Frame('Inventory',Column(children:[Row(children:[const Expanded(child:Text('Items / Stock',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900))),IconButton(tooltip:'Add Item',onPressed:()=>openPage(c,const ItemForm()),icon:const Icon(Icons.add_circle_rounded,color:emerald,size:34))]),if(a.isEmpty)const Empty('No items yet. Tap + to add item.'),...a.asMap().entries.map((e)=>Card(elevation:0,child:ListTile(leading:const CircleAvatar(backgroundColor:emeraldSoft,child:Icon(Icons.inventory_2,color:emerald)),title:Text('${e.value['name']}',style:const TextStyle(fontWeight:FontWeight.w900)),subtitle:Text('Code ${e.value['code']??''} • Rent ${e.value['rentPrice']??15}/100'),trailing:Text('${e.value['quantity']??0}',style:const TextStyle(fontSize:18,fontWeight:FontWeight.w900)),onTap:()=>openPage(c,ItemForm(index:e.key))))]));}}
class ItemForm extends StatefulWidget{final int?index;const ItemForm({super.key,this.index});@override State<ItemForm>createState()=>_ItemState();}
class _ItemState extends State<ItemForm>{late TextEditingController code,name,unit,qty,rent;@override void initState(){super.initState();final x=widget.index==null?<String,dynamic>{}:db.records('items')[widget.index!];code=TextEditingController(text:'${x['code']??''}');name=TextEditingController(text:'${x['name']??''}');unit=TextEditingController(text:'${x['unit']??'pcs'}');qty=TextEditingController(text:'${x['quantity']??0}');rent=TextEditingController(text:'${x['rentPrice']??15}');}@override void dispose(){code.dispose();name.dispose();unit.dispose();qty.dispose();rent.dispose();super.dispose();}Future<void>save()async{if(name.text.trim().isEmpty)return;final old=widget.index==null?null:db.records('items')[widget.index!];final d={'id':old?['id']??uid(),'code':code.text.trim(),'name':name.text.trim(),'unit':unit.text.trim().isEmpty?'pcs':unit.text.trim(),'quantity':int.tryParse(qty.text)??0,'rentPrice':double.tryParse(rent.text)??15};if(widget.index==null)await db.addRecord('items',d);else await db.editRecord('items',widget.index!,d);if(mounted)Navigator.pop(context);}@override Widget build(BuildContext c)=>Frame(widget.index==null?'Add Item':'Edit Item',Column(children:[Field('Item Code',code),Field('Item Name / Description',name),Row(children:[Expanded(child:Field('Unit',unit)),const SizedBox(width:10),Expanded(child:Field('Quantity',qty,type:TextInputType.number))]),Field('Rent Price / 100',rent,type:const TextInputType.numberWithOptions(decimal:true)),SaveBtn('Save Item',save)]));}

class CustomersPage extends StatelessWidget{const CustomersPage({super.key});@override Widget build(BuildContext c){final a=db.records('customers');return Frame('Customers / Parties',Column(children:[Row(children:[const Expanded(child:Text('Party Master',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900))),IconButton(tooltip:'Add Customer',onPressed:()=>openPage(c,const CustomerForm()),icon:const Icon(Icons.person_add_rounded,color:emerald,size:32))]),if(a.isEmpty)const Empty('No parties. Tap + to add.'),...a.asMap().entries.map((e)=>Card(elevation:0,child:ListTile(leading:const Icon(Icons.person,color:emerald),title:Text('${e.value['name']}',style:const TextStyle(fontWeight:FontWeight.w900)),subtitle:Text('${e.value['mobile']??''}\n${e.value['address']??''}'),onTap:()=>openPage(c,CustomerForm(index:e.key))))]));}}
class CustomerForm extends StatefulWidget{final int?index;const CustomerForm({super.key,this.index});@override State<CustomerForm>createState()=>_CustomerState();}
class _CustomerState extends State<CustomerForm>{late TextEditingController n,m,a;@override void initState(){super.initState();final x=widget.index==null?<String,dynamic>{}:db.records('customers')[widget.index!];n=TextEditingController(text:'${x['name']??''}');m=TextEditingController(text:'${x['mobile']??''}');a=TextEditingController(text:'${x['address']??''}');}@override void dispose(){n.dispose();m.dispose();a.dispose();super.dispose();}Future<void>save()async{if(n.text.trim().isEmpty)return;final old=widget.index==null?null:db.records('customers')[widget.index!];final d={'id':old?['id']??uid(),'name':n.text.trim(),'mobile':m.text.trim(),'address':a.text.trim()};if(widget.index==null)await db.addRecord('customers',d);else await db.editRecord('customers',widget.index!,d);if(mounted)Navigator.pop(context);}@override Widget build(BuildContext c)=>Frame(widget.index==null?'Add Customer / Party':'Edit Customer',Column(children:[Field('Customer Name',n),Field('Mobile Number',m,type:TextInputType.phone),Field('Address',a,maxLines:3),SaveBtn('Save Customer',save)]));}

class IssuePage extends StatefulWidget{const IssuePage({super.key});@override State<IssuePage>createState()=>_IssueState();}
class _IssueState extends State<IssuePage>{String? customer;final invoice=TextEditingController();final rows=<Map<String,dynamic>>[];@override void initState(){super.initState();invoice.text='INV-${DateTime.now().millisecondsSinceEpoch}';}@override void dispose(){invoice.dispose();super.dispose();}void addRow(){final a=db.records('items');if(a.isNotEmpty)setState(()=>rows.add({'itemId':a.first['id'],'name':a.first['name'],'qty':1,'rentPrice':a.first['rentPrice']??15}));}Future<void>save()async{if(customer==null||rows.isEmpty)return;await db.addRecord('issues',{'id':uid(),'invoice':invoice.text.trim(),'customerId':customer,'issueDate':today(),'items':rows.map((e)=>Map<String,dynamic>.from(e)).toList()});for(final x in rows)await db.stock('${x['itemId']}',-(int.tryParse('${x['qty']}')??0));if(mounted)Navigator.pop(context);}@override Widget build(BuildContext c){final customers=db.records('customers'),items=db.records('items');return Frame('Issued / New Invoice',Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Row(children:[Expanded(child:DropdownButtonFormField<String>(value:customer,decoration:const InputDecoration(labelText:'Customer / Party'),items:customers.map((x)=>DropdownMenuItem(value:'${x['id']}',child:Text('${x['name']}'))).toList(),onChanged:(v)=>setState(()=>customer=v))),IconButton(tooltip:'Add Customer',onPressed:()=>openPage(c,const CustomerForm()),icon:const Icon(Icons.add_circle_rounded,color:emerald,size:32))]),const SizedBox(height:10),Field('Invoice Number',invoice),if(items.isEmpty)const Empty('Add an inventory item first.'),...rows.asMap().entries.map((e){final x=e.value,i=e.key;return Card(elevation:0,child:Padding(padding:const EdgeInsets.all(10),child:Row(children:[Expanded(child:DropdownButtonFormField<String>(value:'${x['itemId']}',decoration:const InputDecoration(labelText:'Item'),items:items.map((z)=>DropdownMenuItem(value:'${z['id']}',child:Text('${z['name']}'))).toList(),onChanged:(v){final z=items.firstWhere((q)=>'${q['id']}'==v);setState((){x['itemId']=v;x['name']=z['name'];x['rentPrice']=z['rentPrice']??15;});})),const SizedBox(width:8),SizedBox(width:75,child:TextFormField(initialValue:'${x['qty']}',keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Qty'),onChanged:(v)=>x['qty']=int.tryParse(v)??1)),IconButton(onPressed:()=>setState(()=>rows.removeAt(i)),icon:const Icon(Icons.delete_outline,color:Colors.red))])));}),TextButton.icon(onPressed:addRow,icon:const Icon(Icons.add_circle,color:emerald),label:const Text('Add Another Item')),const SizedBox(height:10),SaveBtn('Save Issued Invoice',save)]));}}

class ReturnPage extends StatefulWidget{const ReturnPage({super.key});@override State<ReturnPage>createState()=>_ReturnState();}
class _ReturnState extends State<ReturnPage>{String? customer;Map<String,dynamic>? issue;final selected=<String,int>{};final manual=TextEditingController();final notes=TextEditingController();@override void dispose(){manual.dispose();notes.dispose();super.dispose();}Future<void>save()async{if(issue==null)return;final rd=today();final out=<Map<String,dynamic>>[];double total=0;final d=daysBetween('${issue!['issueDate']}',rd);for(final x in maps(issue!['items'])){final q=selected['${x['itemId']}']??0;if(q<=0)continue;final r=double.tryParse('${x['rentPrice']??15}')??15;final line=r*q*d/100;total+=line;out.add({'itemId':x['itemId'],'name':x['name'],'issuedQty':x['qty'],'returnQty':q,'rentPrice':r,'rentDays':d,'amount':line});await db.stock('${x['itemId']}',q);}if(out.isEmpty)return;final manualAmount=double.tryParse(manual.text);if(manualAmount!=null)total=manualAmount;await db.addRecord('returns',{'id':uid(),'returnInvoice':'RET-${DateTime.now().millisecondsSinceEpoch}','customerId':customer,'issueInvoice':issue!['invoice'],'issueDate':issue!['issueDate'],'returnDate':rd,'rentDays':d,'amount':total,'notes':notes.text.trim(),'items':out});if(mounted)Navigator.pop(context);}@override Widget build(BuildContext c){final customers=db.records('customers'),issues=db.records('issues');final items=issue==null?<Map<String,dynamic>>[]:maps(issue!['items']);return Frame('Return / Receive',Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Row(children:[Expanded(child:DropdownButtonFormField<String>(value:customer,decoration:const InputDecoration(labelText:'Customer / Party'),items:customers.map((x)=>DropdownMenuItem(value:'${x['id']}',child:Text('${x['name']}'))).toList(),onChanged:(v)=>setState((){customer=v;issue=null;selected.clear();}))),IconButton(tooltip:'Add Customer',onPressed:()=>openPage(c,const CustomerForm()),icon:const Icon(Icons.add_circle_rounded,color:emerald,size:32))]),const SizedBox(height:10),DropdownButtonFormField<String>(value:issue?['id']?.toString(),decoration:const InputDecoration(labelText:'Issued Invoice'),items:issues.where((x)=>customer==null||'${x['customerId']}'==customer).map((x)=>DropdownMenuItem(value:'${x['id']}',child:Text('${x['invoice']} • ${x['issueDate']}'))).toList(),onChanged:(v){final x=issues.firstWhere((q)=>'${q['id']}'==v);setState((){issue=x;selected.clear();});}),if(issue!=null)...[const SizedBox(height:10),Text('Issued Date: ${issue!['issueDate']}  •  Return Date: ${today()}',style:const TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:8),...items.map((x)=>ReturnItem(item:x,issueDate:'${issue!['issueDate']}',qty:selected['${x['itemId']}']??0,onChanged:(q)=>setState(()=>selected['${x['itemId']}']=q))),Field('Manual Return Amount (optional)',manual,type:const TextInputType.numberWithOptions(decimal:true)),Field('Notes',notes,maxLines:3),SaveBtn('Save Return & Receipt',save)]));}}
class ReturnItem extends StatelessWidget{final Map<String,dynamic>item;final String issueDate;final int qty;final ValueChanged<int>onChanged;const ReturnItem({super.key,required this.item,required this.issueDate,required this.qty,required this.onChanged});@override Widget build(BuildContext c){final max=int.tryParse('${item['qty']??0}')??0;final r=double.tryParse('${item['rentPrice']??15}')??15;final d=daysBetween(issueDate,today());return Card(elevation:0,color:qty>0?emeraldSoft:Colors.white,child:Padding(padding:const EdgeInsets.all(12),child:Row(children:[const Icon(Icons.inventory_2_outlined,color:emerald),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${item['name']}',style:const TextStyle(fontWeight:FontWeight.w900)),Text('Issued Qty $max • Return Qty $qty'),Text('Rent Price $r/100 • Rent Days $d • Amount ${money(r*qty*d/100)}',style:const TextStyle(color:emeraldDark,fontWeight:FontWeight.w800))])),SizedBox(width:78,child:TextFormField(initialValue:qty==0?'':'$qty',keyboardType:TextInputType.number,decoration:InputDecoration(labelText:'Return',hintText:'0-$max'),onChanged:(v)=>onChanged((int.tryParse(v)??0).clamp(0,max))))])));}}

class InventoryPage extends StatelessWidget{const InventoryPage({super.key});@override Widget build(BuildContext c){final a=db.records('items');return Frame('Inventory Register',Column(children:[if(a.isEmpty)const Empty('No inventory records.'),...a.map((x)=>Card(elevation:0,child:ListTile(title:Text('${x['name']}',style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('Code ${x['code']??''} • Rent ${x['rentPrice']??15}/100'),trailing:Text('${x['quantity']??0}',style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900,color:emerald))))]));}}
String partyName(String? id){for(final x in db.records('customers')){if('${x['id']}'==id)return'${x['name']}';}return'Party';}
class BillsPage extends StatelessWidget{const BillsPage({super.key});@override Widget build(BuildContext c){final issues=db.records('issues'),returns=db.records('returns');return Frame('Reports / Bills',Column(children:[const Align(alignment:Alignment.centerLeft,child:Text('ISSUED BILLS',style:TextStyle(fontWeight:FontWeight.w900,color:emeraldDark))),if(issues.isEmpty)const Empty('No issued bills yet.'),...issues.map((x)=>billTile(c,x,false)),const SizedBox(height:12),const Align(alignment:Alignment.centerLeft,child:Text('RETURN RECEIPTS',style:TextStyle(fontWeight:FontWeight.w900,color:emeraldDark))),if(returns.isEmpty)const Empty('No return receipts yet.'),...returns.map((x)=>billTile(c,x,true))]));}
Widget billTile(BuildContext c,Map<String,dynamic>x,bool ret)=>Card(elevation:0,child:ListTile(leading:Icon(ret?Icons.assignment_return:Icons.receipt_long,color:emerald),title:Text('${x[ret?'returnInvoice':'invoice']} • ${partyName('${x['customerId']}')}',style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text(ret?'Issued ${x['issueDate']} • Return ${x['returnDate']} • Rent Days ${x['rentDays']} • ${money(x['amount'])}':'Issued ${x['issueDate']} • ${maps(x['items']).length} item(s)'),trailing:Wrap(children:[IconButton(tooltip:'Preview / Print PDF',onPressed:()=>pdfPreview(c,x,isReturn:ret),icon:const Icon(Icons.picture_as_pdf,color:emerald)),IconButton(tooltip:'Save / Share PDF',onPressed:()=>pdfShare(x,isReturn:ret),icon:const Icon(Icons.share,color:emerald))]));}
}
Future<pw.Document> makePdf(Map<String,dynamic>x,{bool isReturn=false})async{final doc=pw.Document();final items=maps(x['items']);doc.addPage(pw.MultiPage(pageFormat:pw.PdfPageFormat.a4,build:(_)=>[pw.Text('${db.shop['name']??'RentFlow'}',style:pw.TextStyle(fontSize:22,fontWeight:pw.FontWeight.bold)),pw.Text('${db.shop['address']??''}  ${db.shop['mobile']??''}'),pw.SizedBox(height:10),pw.Text(isReturn?'RETURN RECEIPT':'RENTAL ISSUE INVOICE',style:pw.TextStyle(fontSize:18,fontWeight:pw.FontWeight.bold)),pw.Text('Party: ${partyName('${x['customerId']}')}'),pw.Text('Invoice: ${x[isReturn?'returnInvoice':'invoice']??''}'),pw.Text('Issued Date: ${x['issueDate']??''}'),if(isReturn)pw.Text('Return Date: ${x['returnDate']??''}'),pw.SizedBox(height:12),pw.TableHelper.fromTextArray(headers:isReturn?['Item','Issued Qty','Return Qty','Rent/100','Rent Days','Amount']:['Item','Qty','Rent/100'],data:items.map((i)=>isReturn?['${i['name']}','${i['issuedQty']}','${i['returnQty']}','${i['rentPrice']}','${i['rentDays']}','${money(i['amount'])}']:['${i['name']}','${i['qty']}','${i['rentPrice']}']).toList()),if(isReturn)pw.Padding(padding:const pw.EdgeInsets.only(top:12),child:pw.Text('Total: ${money(x['amount'])}',style:pw.TextStyle(fontSize:16,fontWeight:pw.FontWeight.bold))),pw.SizedBox(height:24),pw.Text('By PaliaAPK HUB • Developer by shanpalia')]);return doc;}
Future<void>pdfPreview(BuildContext c,Map<String,dynamic>x,{bool isReturn=false})async{final doc=await makePdf(x,isReturn:isReturn);if(!c.mounted)return;await Printing.layoutPdf(onLayout:(_)=>doc.save());}
Future<void>pdfShare(Map<String,dynamic>x,{bool isReturn=false})async{final doc=await makePdf(x,isReturn:isReturn);await Printing.sharePdf(bytes:await doc.save(),filename:'${x[isReturn?'returnInvoice':'invoice']??'rentflow'}.pdf');}
class Empty extends StatelessWidget{final String text;const Empty(this.text,{super.key});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.all(24),child:Center(child:Text(text,textAlign:TextAlign.center,style:const TextStyle(color:Colors.black54))));}
class SettingsPage extends StatelessWidget{const SettingsPage({super.key});@override Widget build(BuildContext c)=>Frame('Settings / About',Column(children:[Card(elevation:0,child:ListTile(leading:const Icon(Icons.info_outline,color:emerald),title:const Text('RentFlow',style:TextStyle(fontWeight:FontWeight.w900)),subtitle:const Text('Rental Management • By PaliaAPK HUB • Developer by shanpalia'))),Card(elevation:0,child:ListTile(leading:const Icon(Icons.store_rounded,color:emerald),title:const Text('Shop / Company'),onTap:()=>openPage(c,const ShopPage()))]));}
